//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrathCombo.Resources.Localization.UI.Misc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MiscUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MiscUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WrathCombo.Resources.Localization.UI.Misc.MiscUI", typeof(MiscUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bozja.
        /// </summary>
        internal static string Bozja {
            get {
                return ResourceManager.GetString("Bozja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOL.
        /// </summary>
        internal static string DOL {
            get {
                return ResourceManager.GetString("DOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Roles.
        /// </summary>
        internal static string Job_Roles {
            get {
                return ResourceManager.GetString("Job Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occult Crescent.
        /// </summary>
        internal static string Occult_Crescent {
            get {
                return ResourceManager.GetString("Occult Crescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise.
        /// </summary>
        internal static string Raise {
            get {
                return ResourceManager.GetString("Raise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaces.
        /// </summary>
        internal static string Replaces {
            get {
                return ResourceManager.GetString("Replaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles and Content.
        /// </summary>
        internal static string Roles_and_Content {
            get {
                return ResourceManager.GetString("Roles and Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variant.
        /// </summary>
        internal static string Variant {
            get {
                return ResourceManager.GetString("Variant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variant Dungeons.
        /// </summary>
        internal static string Variant_Dungeons {
            get {
                return ResourceManager.GetString("Variant Dungeons", resourceCulture);
            }
        }
    }
}
