//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrathCombo.Resources.Localization.UI.AutoRotation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AutoRotationUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AutoRotationUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WrathCombo.Resources.Localization.UI.AutoRotation.AutoRotationUI", typeof(AutoRotationUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete From Ignored.
        /// </summary>
        internal static string Button_DeleteFromIgnored {
            get {
                return ResourceManager.GetString("Button_DeleteFromIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-{0}.
        /// </summary>
        internal static string Checkbox_AutoCleanse {
            get {
                return ResourceManager.GetString("Checkbox_AutoCleanse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Resurrect.
        /// </summary>
        internal static string Checkbox_AutoRez {
            get {
                return ResourceManager.GetString("Checkbox_AutoRez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply to {0} &amp; {1}.
        /// </summary>
        internal static string Checkbox_AutoRezDPSJobs {
            get {
                return ResourceManager.GetString("Checkbox_AutoRezDPSJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Raise Raisers.
        /// </summary>
        internal static string Checkbox_AutoRezDPSJobsHealersOnly {
            get {
                return ResourceManager.GetString("Checkbox_AutoRezDPSJobsHealersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply to Out of Party Members.
        /// </summary>
        internal static string Checkbox_AutoRezOutOfParty {
            get {
                return ResourceManager.GetString("Checkbox_AutoRezOutOfParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require {0}/{1}.
        /// </summary>
        internal static string Checkbox_AutoRezRequireSwift {
            get {
                return ResourceManager.GetString("Checkbox_AutoRezRequireSwift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bypass Only in Combat for FATE Targets.
        /// </summary>
        internal static string Checkbox_BypassFATETargets {
            get {
                return ResourceManager.GetString("Checkbox_BypassFATETargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bypass Only in Combat for Quest Targets.
        /// </summary>
        internal static string Checkbox_BypassQuestTargets {
            get {
                return ResourceManager.GetString("Checkbox_BypassQuestTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bypass When Combo Suggests Self-Use Action.
        /// </summary>
        internal static string Checkbox_BypassSelfUse {
            get {
                return ResourceManager.GetString("Checkbox_BypassSelfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable After Leaving Instanced Content.
        /// </summary>
        internal static string Checkbox_DisableInstanceExit {
            get {
                return ResourceManager.GetString("Checkbox_DisableInstanceExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always Set Hard Target.
        /// </summary>
        internal static string Checkbox_DPSAlwaysHardTarget {
            get {
                return ResourceManager.GetString("Checkbox_DPSAlwaysHardTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Auto-Rotation.
        /// </summary>
        internal static string Checkbox_EnableAutoRotation {
            get {
                return ResourceManager.GetString("Checkbox_EnableAutoRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Automatically in Instanced Content.
        /// </summary>
        internal static string Checkbox_EnableInstancedEnter {
            get {
                return ResourceManager.GetString("Checkbox_EnableInstancedEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforce Best AoE Target Selection.
        /// </summary>
        internal static string Checkbox_EnforceBestAoETarget {
            get {
                return ResourceManager.GetString("Checkbox_EnforceBestAoETarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prioritise FATE Targets.
        /// </summary>
        internal static string Checkbox_FATEPriority {
            get {
                return ResourceManager.GetString("Checkbox_FATEPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle Detected Raidwides.
        /// </summary>
        internal static string Checkbox_HandleRaidwides {
            get {
                return ResourceManager.GetString("Checkbox_HandleRaidwides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle Detected Tankbusters.
        /// </summary>
        internal static string Checkbox_HandleTankbusters {
            get {
                return ResourceManager.GetString("Checkbox_HandleTankbusters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always Set Hard Target###HealerHardTarget.
        /// </summary>
        internal static string Checkbox_HealerAlwaysHardTarget {
            get {
                return ResourceManager.GetString("Checkbox_HealerAlwaysHardTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heal Friendly NPCs.
        /// </summary>
        internal static string Checkbox_IncludeNPCs {
            get {
                return ResourceManager.GetString("Checkbox_IncludeNPCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit {0} swapping to tanks only.
        /// </summary>
        internal static string Checkbox_KardiaTanksOnly {
            get {
                return ResourceManager.GetString("Checkbox_KardiaTanksOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Automatically Manage {1}.
        /// </summary>
        internal static string Checkbox_ManageKardia {
            get {
                return ResourceManager.GetString("Checkbox_ManageKardia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Attack Targets Already In Combat.
        /// </summary>
        internal static string Checkbox_OnlyAttackInCombat {
            get {
                return ResourceManager.GetString("Checkbox_OnlyAttackInCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only in Combat.
        /// </summary>
        internal static string Checkbox_OnlyInCombat {
            get {
                return ResourceManager.GetString("Checkbox_OnlyInCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Orbwalker Integration.
        /// </summary>
        internal static string Checkbox_Orbwalker {
            get {
                return ResourceManager.GetString("Checkbox_Orbwalker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}/{1}/{2}/{3}] Pre-emptively apply Heal Over Time/Shields on focus target.
        /// </summary>
        internal static string Checkbox_PreEmptiveHoT {
            get {
                return ResourceManager.GetString("Checkbox_PreEmptiveHoT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prioritise Targets Not in Combat.
        /// </summary>
        internal static string Checkbox_PreferNonCombat {
            get {
                return ResourceManager.GetString("Checkbox_PreferNonCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prioritise Quest Targets.
        /// </summary>
        internal static string Checkbox_QuestPriority {
            get {
                return ResourceManager.GetString("Checkbox_QuestPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un-Target and Stop Actions for Pyretics.
        /// </summary>
        internal static string Checkbox_UnTargetAndDisableForPenalty {
            get {
                return ResourceManager.GetString("Checkbox_UnTargetAndDisableForPenalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healing Settings.
        /// </summary>
        internal static string Header_HealingSettings {
            get {
                return ResourceManager.GetString("Header_HealingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling this will turn off AoE Healing features. Otherwise will require the amount of targets required to be in range of an AoE feature&apos;s heal to use..
        /// </summary>
        internal static string HelpText_AoEHealTargetCount {
            get {
                return ResourceManager.GetString("HelpText_AoEHealTargetCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling this will turn off AoE DPS features. Otherwise will require the amount of targets required to be in range of an AoE feature&apos;s attack to use. This applies to all 3 roles, and for any features that deal AoE damage..
        /// </summary>
        internal static string HelpText_AoETargetCount {
            get {
                return ResourceManager.GetString("HelpText_AoETargetCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will {0} any cleansable debuffs (Healing takes priority)..
        /// </summary>
        internal static string HelpText_AutoCleanse {
            get {
                return ResourceManager.GetString("HelpText_AutoCleanse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will attempt to resurrect dead party members.
        ///Applies to {0}, {1}, {2}, {3}, {4}, and {5} {6} {7}.
        /// </summary>
        internal static string HelpText_AutoRez {
            get {
                return ResourceManager.GetString("HelpText_AutoRez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When playing as {0} or {1}, also attempt to raise a dead party member. {2} will only resurrect with {3} or {4} active..
        /// </summary>
        internal static string HelpText_AutoRezDPSJobs {
            get {
                return ResourceManager.GetString("HelpText_AutoRezDPSJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When playing as {0} or {1}, Will only attempt to res Healers and Raisers.
        /// </summary>
        internal static string HelpText_AutoRezDPSJobsHealersOnly {
            get {
                return ResourceManager.GetString("HelpText_AutoRezDPSJobsHealersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires {0} or {1}&apos;s {2} to be available to resurrect a party member, to avoid hard-casting..
        /// </summary>
        internal static string HelpText_AutoRezRequireSwift {
            get {
                return ResourceManager.GetString("HelpText_AutoRezRequireSwift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables Auto-Mode outside of combat unless you&apos;re synced to a FATE..
        /// </summary>
        internal static string HelpText_BypassFATETargets {
            get {
                return ResourceManager.GetString("HelpText_BypassFATETargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables Auto-Mode outside of combat unless you&apos;re within range of a quest target..
        /// </summary>
        internal static string HelpText_BypassQuestTargets {
            get {
                return ResourceManager.GetString("HelpText_BypassQuestTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many jobs have an out of combat action that can be used, for example, {0} or {1}. This will allow these to be used without being in combat..
        /// </summary>
        internal static string HelpText_BypassSelfUse {
            get {
                return ResourceManager.GetString("HelpText_BypassSelfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-rotation does not need to target enemies to work, however with this setting enabled it will always set your hard target when it executes an attack..
        /// </summary>
        internal static string HelpText_DPSAlwaysHardTarget {
            get {
                return ResourceManager.GetString("HelpText_DPSAlwaysHardTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max distance all targeting modes (except Manual) will look for a target. Values from 1 to 30 only..
        /// </summary>
        internal static string HelpText_DPSMaxTargetDistance {
            get {
                return ResourceManager.GetString("HelpText_DPSMaxTargetDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual - Leaves all targeting decisions to you.
        ///Highest Max - Prioritises enemies with the highest max HP.
        ///Lowest Max - Prioritises enemies with the lowest max HP.
        ///Highest Current - Prioritises the enemy with the highest current HP.
        ///Lowest Current - Prioritises the enemy with the lowest current HP.
        ///Tank Target - Prioritises the same target as the first tank in your group.
        ///Nearest - Prioritises the closest target to you.
        ///Furthest - Prioritises the furthest target from you..
        /// </summary>
        internal static string HelpText_DPSTargettingMode {
            get {
                return ResourceManager.GetString("HelpText_DPSTargettingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For all other targeting modes, AoE will target based on highest number of targets hit. In manual mode, it will only do this if you tick this box..
        /// </summary>
        internal static string HelpText_EnforceBestAoETarget {
            get {
                return ResourceManager.GetString("HelpText_EnforceBestAoETarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will try to use actions before detected raidwides or group damage to either mitigate or top-off party members. Max 2 actions (excluding {0} for setup).
        /// </summary>
        internal static string HelpText_HandleRaidwides {
            get {
                return ResourceManager.GetString("HelpText_HandleRaidwides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will try to use actions before detected tankbusters to mitigate damage on targeted member. Max 1 action (excluding {0} for setup).
        /// </summary>
        internal static string HelpText_HandleTankbusters {
            get {
                return ResourceManager.GetString("HelpText_HandleTankbusters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t set this too high! 1-2 seconds is normally comfy enough to be considered a natural reaction..
        /// </summary>
        internal static string HelpText_HealDelay {
            get {
                return ResourceManager.GetString("HelpText_HealDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-rotation does not need to target allies to work, however with this setting enabled it will always set your hard target when it executes a heal..
        /// </summary>
        internal static string HelpText_HealerAlwaysHardTarget {
            get {
                return ResourceManager.GetString("HelpText_HealerAlwaysHardTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual - Will only heal a target if you select them manually. If the target does not meet the healing threshold settings criteria below it will skip healing in favour of DPSing (if also enabled).
        ///Highest Current - Prioritises the party member with the highest current HP%.
        ///Lowest Current - Prioritises the party member with the lowest current HP%..
        /// </summary>
        internal static string HelpText_HealerTargetingMode {
            get {
                return ResourceManager.GetString("HelpText_HealerTargetingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These NPCs will be ignored by Auto-Rotation.
        ///Every instance of this NPC will be excluded from automatic targeting (Manual will still work).
        ///To remove an NPC from this list, select it and press the Delete button below.
        ///To add an NPC to this list, target the NPC and use the command: /qoltweaks ignore.
        /// </summary>
        internal static string HelpText_IgnoredNPCs {
            get {
                return ResourceManager.GetString("HelpText_IgnoredNPCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When in boss fights only, any target regardless of distance can be eligible to be attacked..
        /// </summary>
        internal static string HelpText_IgnoreRangeInBoss {
            get {
                return ResourceManager.GetString("HelpText_IgnoreRangeInBoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful for healer quests where NPCs are expected to be healed but aren&apos;t added directly to your party..
        /// </summary>
        internal static string HelpText_IncludeNPCs {
            get {
                return ResourceManager.GetString("HelpText_IncludeNPCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switches {0} to party members currently being targeted by enemies, prioritising tanks if multiple people are being targeted..
        /// </summary>
        internal static string HelpText_ManageKardia {
            get {
                return ResourceManager.GetString("HelpText_ManageKardia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will make Auto-Rotation use actions with cast times even whilst moving, as Orbwalker will lock movement during the cast. You may need to enable &quot;Buffer Initial Cast&quot; setting in Orbwalker if not already enabled. Requires an Orbwalker plugin to be installed and enabled..
        /// </summary>
        internal static string HelpText_Orbwalker {
            get {
                return ResourceManager.GetString("HelpText_Orbwalker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies {0}/{1}/{2}/{3} to your focus target when out of combat and they are 30y or less away from an enemy. (Bypasses &quot;Only in Combat&quot; setting).
        /// </summary>
        internal static string HelpText_PreEmptiveHoT {
            get {
                return ResourceManager.GetString("HelpText_PreEmptiveHoT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will determine how soon before the GCD is finished to queue up the next weaponskill or spell. Your latency may have an effect on what actions are performed so please adjust this if you&apos;re noticing improper action use, i.e double Blizzard IV casts due to MP not updating in time..
        /// </summary>
        internal static string HelpText_QueueWindow {
            get {
                return ResourceManager.GetString("HelpText_QueueWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You typically want to set this lower than the above setting..
        /// </summary>
        internal static string HelpText_SingleTargetExcogHPP {
            get {
                return ResourceManager.GetString("HelpText_SingleTargetExcogHPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You typically want to set this lower than the above setting..
        /// </summary>
        internal static string HelpText_SingleTargetRegenHPP {
            get {
                return ResourceManager.GetString("HelpText_SingleTargetRegenHPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Rotation has a built in throttler to only run every so many milliseconds for performance reasons. If you experience issues with frame rate, try increasing this value. Do note this may have a side-effect of introducing clipping if set too high, so experiment with the value..
        /// </summary>
        internal static string HelpText_ThrottleDelay {
            get {
                return ResourceManager.GetString("HelpText_ThrottleDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will un-set any current target and disable Auto-Rotation actions if there is a current detected Pyretic (or similar, like Acceleration Bomb) mechanic affecting the player, that would harm them if they took any action..
        /// </summary>
        internal static string HelpText_UnTargetAndDisableForPenalty {
            get {
                return ResourceManager.GetString("HelpText_UnTargetAndDisableForPenalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is where you can configure the parameters in which Auto-Rotation will operate.
        ///Features marked with an &apos;Auto-Mode&apos; checkbox are able to be used with Auto-Rotation..
        /// </summary>
        internal static string Info_Header {
            get {
                return ResourceManager.GetString("Info_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targets Required for AoE Healing Features.
        /// </summary>
        internal static string Input_AoEHealTargetCount {
            get {
                return ResourceManager.GetString("Input_AoEHealTargetCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targets Required for AoE Damage Features.
        /// </summary>
        internal static string Input_AoETargetCount {
            get {
                return ResourceManager.GetString("Input_AoETargetCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay to activate Auto-Rotation once combat starts (seconds).
        /// </summary>
        internal static string Input_AutoRotationDelay {
            get {
                return ResourceManager.GetString("Input_AutoRotationDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay to start healing once above conditions are met (seconds).
        /// </summary>
        internal static string Input_HealDelay {
            get {
                return ResourceManager.GetString("Input_HealDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue Window (s).
        /// </summary>
        internal static string Input_QueueWindow {
            get {
                return ResourceManager.GetString("Input_QueueWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throttle Delay (ms).
        /// </summary>
        internal static string Input_ThrottleDelay {
            get {
                return ResourceManager.GetString("Input_ThrottleDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string Label_Advanced {
            get {
                return ResourceManager.GetString("Label_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Settings.
        /// </summary>
        internal static string Label_DamageSettings {
            get {
                return ResourceManager.GetString("Label_DamageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Target Distance.
        /// </summary>
        internal static string Label_DPSMaxTargetDistance {
            get {
                return ResourceManager.GetString("Label_DPSMaxTargetDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targeting Mode.
        /// </summary>
        internal static string Label_DPSTargetingMode {
            get {
                return ResourceManager.GetString("Label_DPSTargetingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healer Targeting Mode.
        /// </summary>
        internal static string Label_HealingTargetingMode {
            get {
                return ResourceManager.GetString("Label_HealingTargetingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored NPCs.
        /// </summary>
        internal static string Label_IgnoredNPCs {
            get {
                return ResourceManager.GetString("Label_IgnoredNPCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Max Target Distance In Boss Fights.
        /// </summary>
        internal static string Label_IgnoreRangeInBoss {
            get {
                return ResourceManager.GetString("Label_IgnoreRangeInBoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AoE HP% Threshold.
        /// </summary>
        internal static string Slider_AoETargetHPP {
            get {
                return ResourceManager.GetString("Slider_AoETargetHPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Target HP% Threshold (target has Excogitation).
        /// </summary>
        internal static string Slider_SingleTargetExcogHPP {
            get {
                return ResourceManager.GetString("Slider_SingleTargetExcogHPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Target HP% Threshold.
        /// </summary>
        internal static string Slider_SingleTargetHPP {
            get {
                return ResourceManager.GetString("Slider_SingleTargetHPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Target HP% Threshold (target has Regen/Aspected Benefic).
        /// </summary>
        internal static string Slider_SingleTargetRegenHPP {
            get {
                return ResourceManager.GetString("Slider_SingleTargetRegenHPP", resourceCulture);
            }
        }
    }
}
