//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrathCombo.Resources.Localization.JobConfigs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BLM_Config {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BLM_Config() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WrathCombo.Resources.Localization.JobConfigs.BLM_Config", typeof(BLM_Config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds {0} / {1} / {2} in {3} depending on stacks and level.
        /// </summary>
        internal static string Add0or1or2or3DependingonStackAndLevel {
            get {
                return ResourceManager.GetString("Add0or1or2or3DependingonStackAndLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds {0} / {1} when in {2} and stack is less than 3.
        /// </summary>
        internal static string Add0Or1WhenIn2 {
            get {
                return ResourceManager.GetString("Add0Or1WhenIn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds {0} when in {1} and below 2400 MP..
        /// </summary>
        internal static string Add0WhenBelow2400MP {
            get {
                return ResourceManager.GetString("Add0WhenBelow2400MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds {0} when in {1} and above 800 MP..
        /// </summary>
        internal static string Add0WhenIn1AndAbove800MP {
            get {
                return ResourceManager.GetString("Add0WhenIn1AndAbove800MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds {0} in {1} when ready..
        /// </summary>
        internal static string AddFlarestarinAF {
            get {
                return ResourceManager.GetString("AddFlarestarinAF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use while under the effect of {0}.
        ///This is the recommended behaviour..
        /// </summary>
        internal static string DoNotUseUnderLeylines {
            get {
                return ResourceManager.GetString("DoNotUseUnderLeylines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaves {0} in {2} 
        ///Will Use {0} / {1} if selected above..
        /// </summary>
        internal static string DontChangeFireInUmbralIce {
            get {
                return ResourceManager.GetString("DontChangeFireInUmbralIce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will only use {0} when both HP is under the slider threshold, and when groupwide damage is incoming.
        /// </summary>
        internal static string ManawardHPThresholdAndGroupwideDesc {
            get {
                return ResourceManager.GetString("ManawardHPThresholdAndGroupwideDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not under {0}.
        /// </summary>
        internal static string NotUnderLeylines {
            get {
                return ResourceManager.GetString("NotUnderLeylines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only require HP threshold for solo play.
        /// </summary>
        internal static string OnlySolo {
            get {
                return ResourceManager.GetString("OnlySolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When solo (Chocobos do not count), will only require to meet the HP threshold. In a party, it will require both the HP threshold and groupwide damage incoming..
        /// </summary>
        internal static string OnlySoloDesc {
            get {
                return ResourceManager.GetString("OnlySoloDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger only on groupwide damage incoming.
        /// </summary>
        internal static string OnlyTriggerGroupwide {
            get {
                return ResourceManager.GetString("OnlyTriggerGroupwide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will only use {0} when groupwide damage is incoming.
        /// </summary>
        internal static string OnlyTriggerGroupwideDesc {
            get {
                return ResourceManager.GetString("OnlyTriggerGroupwideDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger only on HP threshold.
        /// </summary>
        internal static string OnlyTriggerHP {
            get {
                return ResourceManager.GetString("OnlyTriggerHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will only use {0} when HP is under the slider threshold, and will not wait for any groupwide damage to be detected (mostly for solo-play).
        /// </summary>
        internal static string OnlyTriggerHPDesc {
            get {
                return ResourceManager.GetString("OnlyTriggerHPDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaces {0} with {1} when in {2}..
        /// </summary>
        internal static string ReplaceBlizzard3WithBlizzardWhenInUI3 {
            get {
                return ResourceManager.GetString("ReplaceBlizzard3WithBlizzardWhenInUI3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaces {0} with {1} when out of {2}..
        /// </summary>
        internal static string ReplaceBlizzardWithBlizzard3WhenNotInUI3 {
            get {
                return ResourceManager.GetString("ReplaceBlizzardWithBlizzard3WhenNotInUI3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaces {0} with {1} when in {2}..
        /// </summary>
        internal static string ReplaceFire3WithFireWhenInAF3 {
            get {
                return ResourceManager.GetString("ReplaceFire3WithFireWhenInAF3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaces {0} with {1} when out of {2} or not in combat..
        /// </summary>
        internal static string ReplaceFireWithFire3WhenNotInAF3OrCombat {
            get {
                return ResourceManager.GetString("ReplaceFireWithFire3WhenNotInAF3OrCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require both HP check and groupwide damage incoming.
        /// </summary>
        internal static string RequireHPandGroupwide {
            get {
                return ResourceManager.GetString("RequireHPandGroupwide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makes it so that {0} also shows when {1} is on cooldown..
        /// </summary>
        internal static string ShowXenoglossyWhenAmplifierIsOnCooldown {
            get {
                return ResourceManager.GetString("ShowXenoglossyWhenAmplifierIsOnCooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show {0} when {1} is on cooldown.
        /// </summary>
        internal static string ShowXenoglossyWhenAmplifierOnCD {
            get {
                return ResourceManager.GetString("ShowXenoglossyWhenAmplifierOnCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {0} when below 1500 MP and when it is an instant cast (level 100 only)..
        /// </summary>
        internal static string UseDespairWhenBelow1500MP {
            get {
                return ResourceManager.GetString("UseDespairWhenBelow1500MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {0} when you have {1} proc..
        /// </summary>
        internal static string UseFire3WhenYouHaveFirestarterProc {
            get {
                return ResourceManager.GetString("UseFire3WhenYouHaveFirestarterProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {0} when in {1}..
        /// </summary>
        internal static string UseParadoxWhenInAF3 {
            get {
                return ResourceManager.GetString("UseParadoxWhenInAF3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {0} when you don&apos;t have {1}..
        /// </summary>
        internal static string UseSwiftcastWhenNoTriplecast {
            get {
                return ResourceManager.GetString("UseSwiftcastWhenNoTriplecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {0} when you don&apos;t have {1} active..
        /// </summary>
        internal static string UseTriplecastWhenNoSwiftcast {
            get {
                return ResourceManager.GetString("UseTriplecastWhenNoSwiftcast", resourceCulture);
            }
        }
    }
}
