//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrathCombo.Resources.Localization.JobConfigs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BST_Config {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BST_Config() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WrathCombo.Resources.Localization.JobConfigs.BST_Config", typeof(BST_Config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle Beasts.
        /// </summary>
        internal static string CycleBeasts {
            get {
                return ResourceManager.GetString("CycleBeasts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will cycle beasts in combat using Parting Blow. You may wish to do this manually instead to prevent beasts going on cooldown..
        /// </summary>
        internal static string CycleBeastsDesc {
            get {
                return ResourceManager.GetString("CycleBeastsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform Infinitive Combo?.
        /// </summary>
        internal static string Infinitive {
            get {
                return ResourceManager.GetString("Infinitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds Rally/Rallying cheer to allow performing Infinitive Combos. Infinitive combo will start when you have 100 TP for you and your beast, you have at least 2 Mastered Instinct stacks and at least 1 Natural Instinct stack, with both Rally and Rallying Cheer off cooldown. It will perform this setup before level 50 also, with it adding in the Infinitive combo finisher when you&apos;re level 50..
        /// </summary>
        internal static string InfinitiveDesc {
            get {
                return ResourceManager.GetString("InfinitiveDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum TP for both player and beast.
        /// </summary>
        internal static string MinTPPlayerBeast {
            get {
                return ResourceManager.GetString("MinTPPlayerBeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only replace for horn that borrowed.
        /// </summary>
        internal static string OnlyCurrentHorn {
            get {
                return ResourceManager.GetString("OnlyCurrentHorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you switch away from the horn that borrowed the ability, return the action back to Borrow..
        /// </summary>
        internal static string OnlyCurrentHornDesc {
            get {
                return ResourceManager.GetString("OnlyCurrentHornDesc", resourceCulture);
            }
        }
    }
}
