//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrathCombo.Resources.Localization.JobConfigs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Generics {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Generics() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WrathCombo.Resources.Localization.JobConfigs.Generics", typeof(Generics).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Option.
        /// </summary>
        internal static string _0Option {
            get {
                return ResourceManager.GetString("_0Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Opener.
        /// </summary>
        internal static string Action_Opener {
            get {
                return ResourceManager.GetString("Action_Opener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Priority: .
        /// </summary>
        internal static string Action_Priority {
            get {
                return ResourceManager.GetString("Action_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Threshold.
        /// </summary>
        internal static string Action_Threshold {
            get {
                return ResourceManager.GetString("Action_Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0}.
        /// </summary>
        internal static string Add0 {
            get {
                return ResourceManager.GetString("Add0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0} Combo.
        /// </summary>
        internal static string Add0Combo {
            get {
                return ResourceManager.GetString("Add0Combo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds {0} combo when applicable..
        /// </summary>
        internal static string Add0ComboWhenApplicable {
            get {
                return ResourceManager.GetString("Add0ComboWhenApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0} / {1}..
        /// </summary>
        internal static string Add0Or1 {
            get {
                return ResourceManager.GetString("Add0Or1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0} / {1} when applicable..
        /// </summary>
        internal static string Add0Or1WhenApplicable {
            get {
                return ResourceManager.GetString("Add0Or1WhenApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0} to the rotation..
        /// </summary>
        internal static string Add0ToTheRotation {
            get {
                return ResourceManager.GetString("Add0ToTheRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0} when {1} is ready..
        /// </summary>
        internal static string Add0When1IsReady {
            get {
                return ResourceManager.GetString("Add0When1IsReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0} when applicable..
        /// </summary>
        internal static string Add0WhenApplicable {
            get {
                return ResourceManager.GetString("Add0WhenApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0} when average HP% of the party is at or below..
        /// </summary>
        internal static string Add0WhenAverageHpPercentofPartyIsAtOrBelow {
            get {
                return ResourceManager.GetString("Add0WhenAverageHpPercentofPartyIsAtOrBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds Field mouseover targetting..
        /// </summary>
        internal static string AddFieldMouseoverTargetting {
            get {
                return ResourceManager.GetString("AddFieldMouseoverTargetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds {0} to {1}..
        /// </summary>
        internal static string Adds0To1 {
            get {
                return ResourceManager.GetString("Adds0To1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aligns {0} with {1}..
        /// </summary>
        internal static string Align0With1 {
            get {
                return ResourceManager.GetString("Align0With1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep {0} aligned with manual use of {1}..
        /// </summary>
        internal static string Align0WithManual1 {
            get {
                return ResourceManager.GetString("Align0WithManual1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Content.
        /// </summary>
        internal static string AllContent {
            get {
                return ResourceManager.GetString("AllContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies to all content in the game..
        /// </summary>
        internal static string AllContentDescription {
            get {
                return ResourceManager.GetString("AllContentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Enemies.
        /// </summary>
        internal static string AllEnemies {
            get {
                return ResourceManager.GetString("AllEnemies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Mouseover &gt; Field Mouseover &gt; Focus Target &gt; Soft Target &gt; Hard Target.
        /// </summary>
        internal static string AllHealerRetargetting {
            get {
                return ResourceManager.GetString("AllHealerRetargetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ally Hard Target.
        /// </summary>
        internal static string AllyHardTarget {
            get {
                return ResourceManager.GetString("AllyHardTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ally HP% to be less than or equal to:.
        /// </summary>
        internal static string AllyHPLessOrEqual {
            get {
                return ResourceManager.GetString("AllyHPLessOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        internal static string Always {
            get {
                return ResourceManager.GetString("Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Movement.
        /// </summary>
        internal static string AnyMovement {
            get {
                return ResourceManager.GetString("AnyMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies options to {0} only..
        /// </summary>
        internal static string ApplyOnlyTo0 {
            get {
                return ResourceManager.GetString("ApplyOnlyTo0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies options to all of these:{0}
        ///  .
        /// </summary>
        internal static string ApplyToAll0 {
            get {
                return ResourceManager.GetString("ApplyToAll0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block {0} when with Savage Blade when no stunnable targets are found..
        /// </summary>
        internal static string BlockStun {
            get {
                return ResourceManager.GetString("BlockStun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boss Encounter Non-Bosses: Stop using at Enemy HP %.
        /// </summary>
        internal static string BossEncounterNonBossHpPercent {
            get {
                return ResourceManager.GetString("BossEncounterNonBossHpPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boss-Only Content.
        /// </summary>
        internal static string BossOnlyContent {
            get {
                return ResourceManager.GetString("BossOnlyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only applies in instances where you directly fight a boss.
        ///Excludes many A Realm Reborn &amp; Heavensward raids that include trash..
        /// </summary>
        internal static string BossOnlyDescription {
            get {
                return ResourceManager.GetString("BossOnlyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosses: Stop using at Enemy HP %.
        /// </summary>
        internal static string BossOnlyHpPercent {
            get {
                return ResourceManager.GetString("BossOnlyHpPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burst Option.
        /// </summary>
        internal static string BurstOption {
            get {
                return ResourceManager.GetString("BurstOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change {0} / {1}.
        /// </summary>
        internal static string Change0Or1 {
            get {
                return ResourceManager.GetString("Change0Or1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many charges to retain for manual use.
        ///Set to 0 to disable this check..
        /// </summary>
        internal static string ChargePool {
            get {
                return ResourceManager.GetString("ChargePool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long to delay after detecting incoming tankbuster to use {0}.
        ///Set to 0 to disable this check..
        /// </summary>
        internal static string DelayMit {
            get {
                return ResourceManager.GetString("DelayMit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable range check.
        /// </summary>
        internal static string DisableRangeCheck {
            get {
                return ResourceManager.GetString("DisableRangeCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables the use of mitigations..
        /// </summary>
        internal static string DisablesTheUseOfMitigations {
            get {
                return ResourceManager.GetString("DisablesTheUseOfMitigations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t Use {0}.
        /// </summary>
        internal static string DontUse0 {
            get {
                return ResourceManager.GetString("DontUse0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds remaining before reapplying the DoT.
        ///Set to Zero to disable this check..
        /// </summary>
        internal static string DoTSecondsRemainingZeroDisable {
            get {
                return ResourceManager.GetString("DoTSecondsRemainingZeroDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables the use of mitigations..
        /// </summary>
        internal static string EnablesTheUseOfMitigations {
            get {
                return ResourceManager.GetString("EnablesTheUseOfMitigations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enemy Hard Target.
        /// </summary>
        internal static string EnemyHardTarget {
            get {
                return ResourceManager.GetString("EnemyHardTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select what kind of enemies the HP check should be applied to:.
        /// </summary>
        internal static string EnemyTypeCheck {
            get {
                return ResourceManager.GetString("EnemyTypeCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude {0}.
        /// </summary>
        internal static string Exclude0 {
            get {
                return ResourceManager.GetString("Exclude0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude Advanced Mitigations.
        /// </summary>
        internal static string ExcludeAdvancedMitigations {
            get {
                return ResourceManager.GetString("ExcludeAdvancedMitigations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude Simple Mitigations.
        /// </summary>
        internal static string ExcludeSimpleMitigations {
            get {
                return ResourceManager.GetString("ExcludeSimpleMitigations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Mouseover.
        /// </summary>
        internal static string FieldMouseover {
            get {
                return ResourceManager.GetString("FieldMouseover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus Target.
        /// </summary>
        internal static string FocusTarget {
            get {
                return ResourceManager.GetString("FocusTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Furthest outside of 5y.
        /// </summary>
        internal static string FurthestOOR {
            get {
                return ResourceManager.GetString("FurthestOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will {0} at the furthest hostile outside of 5 Yalms..
        /// </summary>
        internal static string FurthestOORRetarget {
            get {
                return ResourceManager.GetString("FurthestOORRetarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {0} in Opener.
        /// </summary>
        internal static string GapcloserUse {
            get {
                return ResourceManager.GetString("GapcloserUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip {0} in Opener.
        /// </summary>
        internal static string GapcloseSkip {
            get {
                return ResourceManager.GetString("GapcloseSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require a battle target..
        /// </summary>
        internal static string HaveBattleTarget {
            get {
                return ResourceManager.GetString("HaveBattleTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold {0} for {1}.
        /// </summary>
        internal static string Hold0For1 {
            get {
                return ResourceManager.GetString("Hold0For1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many charges to save for movement?.
        /// </summary>
        internal static string HowManyChargesForMovement {
            get {
                return ResourceManager.GetString("HowManyChargesForMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  How many charges to keep ready?
        ///(0 = Use All).
        /// </summary>
        internal static string HowManyChargesToKeepReady {
            get {
                return ResourceManager.GetString("HowManyChargesToKeepReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies HP Check to All Content.
        /// </summary>
        internal static string HPCheckAllContent {
            get {
                return ResourceManager.GetString("HPCheckAllContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies the HP check above to all enemies..
        /// </summary>
        internal static string HPCheckAllEnemies {
            get {
                return ResourceManager.GetString("HPCheckAllEnemies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies HP check to Non-Boss Encounters only.
        /// </summary>
        internal static string HPCheckNonBossEncountersOnly {
            get {
                return ResourceManager.GetString("HPCheckNonBossEncountersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only applies the HP check above to non-bosses..
        /// </summary>
        internal static string HPCheckNonBosses {
            get {
                return ResourceManager.GetString("HPCheckNonBosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a HP% Threshold for when {0} will not be automatically applied to the target..
        /// </summary>
        internal static string HPPercentageFor0NotBeApplied {
            get {
                return ResourceManager.GetString("HPPercentageFor0NotBeApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} HP percentage threshold..
        /// </summary>
        internal static string HPPercentageThreshold {
            get {
                return ResourceManager.GetString("HPPercentageThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HP% Threshold to use all charges of {0}..
        /// </summary>
        internal static string HPPercentThresholdUseAllCharges0 {
            get {
                return ResourceManager.GetString("HPPercentThresholdUseAllCharges0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include {0}.
        /// </summary>
        internal static string Include0 {
            get {
                return ResourceManager.GetString("Include0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Advanced Mitigations.
        /// </summary>
        internal static string IncludeAdvancedMitigations {
            get {
                return ResourceManager.GetString("IncludeAdvancedMitigations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Shields in HP Percent Sliders.
        /// </summary>
        internal static string IncludeShields {
            get {
                return ResourceManager.GetString("IncludeShields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Simple Mitigations.
        /// </summary>
        internal static string IncludeSimpleMitigations {
            get {
                return ResourceManager.GetString("IncludeSimpleMitigations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Melee Range.
        /// </summary>
        internal static string InMeleeRange {
            get {
                return ResourceManager.GetString("InMeleeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In range.
        /// </summary>
        internal static string InRange {
            get {
                return ResourceManager.GetString("InRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Shield Check.
        /// </summary>
        internal static string Job0ShieldCheck {
            get {
                return ResourceManager.GetString("Job0ShieldCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable to not override an existing {0}&apos;s shield..
        /// </summary>
        internal static string Job0ShieldCheckDesc {
            get {
                return ResourceManager.GetString("Job0ShieldCheckDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lockout {0}..
        /// </summary>
        internal static string LockoutAction {
            get {
                return ResourceManager.GetString("LockoutAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lockout when stun has been applied this many times..
        /// </summary>
        internal static string LockoutActionStunCount {
            get {
                return ResourceManager.GetString("LockoutActionStunCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set value for your MP to be at or under for this feature to work.
        /// </summary>
        internal static string LucidMP {
            get {
                return ResourceManager.GetString("LucidMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of targets to employ multi-dotting .
        /// </summary>
        internal static string MaxTargetsMultiDot {
            get {
                return ResourceManager.GetString("MaxTargetsMultiDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Gauge Required to use {0} .
        /// </summary>
        internal static string MinimumGauge {
            get {
                return ResourceManager.GetString("MinimumGauge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Number of enemies in range to use. .
        /// </summary>
        internal static string MinimumNumberOfEnemies {
            get {
                return ResourceManager.GetString("MinimumNumberOfEnemies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouseover.
        /// </summary>
        internal static string Mouseover {
            get {
                return ResourceManager.GetString("Mouseover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will retarget {0} at your mouseover target (if Hostile). Highest Priority..
        /// </summary>
        internal static string MouseoverRetargetHostile {
            get {
                return ResourceManager.GetString("MouseoverRetargetHostile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement Option.
        /// </summary>
        internal static string MovementOption {
            get {
                return ResourceManager.GetString("MovementOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player MP to be greater than or equal to:.
        /// </summary>
        internal static string MPGreaterOrEqual {
            get {
                return ResourceManager.GetString("MPGreaterOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player MP to be less than or equal to:.
        /// </summary>
        internal static string MPLessOrEqual {
            get {
                return ResourceManager.GetString("MPLessOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest outside of 5y.
        /// </summary>
        internal static string NearestOOR {
            get {
                return ResourceManager.GetString("NearestOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will {0} at the nearest hostile outside of 5 Yalms..
        /// </summary>
        internal static string NearestOORRetarget {
            get {
                return ResourceManager.GetString("NearestOORRetarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Movement.
        /// </summary>
        internal static string NoMovement {
            get {
                return ResourceManager.GetString("NoMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-boss Encounters Only.
        /// </summary>
        internal static string NonBossEncountersOnly {
            get {
                return ResourceManager.GetString("NonBossEncountersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Bosses.
        /// </summary>
        internal static string NonBosses {
            get {
                return ResourceManager.GetString("NonBosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Bosses: Stop using at Enemy HP %.
        /// </summary>
        internal static string NonBossHpPercent {
            get {
                return ResourceManager.GetString("NonBossHpPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will start the opener regardless of having a target..
        /// </summary>
        internal static string NoRequireTarget {
            get {
                return ResourceManager.GetString("NoRequireTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Targeting.
        /// </summary>
        internal static string NormalTargeting {
            get {
                return ResourceManager.GetString("NormalTargeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t require a battle target..
        /// </summary>
        internal static string NoTarget {
            get {
                return ResourceManager.GetString("NoTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not In Boss Encounters.
        /// </summary>
        internal static string NotInBossEncounters {
            get {
                return ResourceManager.GetString("NotInBossEncounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On {0}.
        /// </summary>
        internal static string On0 {
            get {
                return ResourceManager.GetString("On0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boss Only.
        /// </summary>
        internal static string OnlyBoss {
            get {
                return ResourceManager.GetString("OnlyBoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only use {0}.
        /// </summary>
        internal static string OnlyUse0 {
            get {
                return ResourceManager.GetString("OnlyUse0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only uses {0} when in melee range..
        /// </summary>
        internal static string OnlyUse0WhenInMeleeRange {
            get {
                return ResourceManager.GetString("OnlyUse0WhenInMeleeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only uses {0} when not moving..
        /// </summary>
        internal static string OnlyUse0WhenNotMoving {
            get {
                return ResourceManager.GetString("OnlyUse0WhenNotMoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only use the opener when a countdown is active..
        /// </summary>
        internal static string OnlyUseOpenerWhenCountdownActive {
            get {
                return ResourceManager.GetString("OnlyUseOpenerWhenCountdownActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only use {0} when the targeted enemy is a boss..
        /// </summary>
        internal static string OnlyUseWhenTargetIsBoss {
            get {
                return ResourceManager.GetString("OnlyUseWhenTargetIsBoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only use with {0}.
        /// </summary>
        internal static string OnlyUseWith0 {
            get {
                return ResourceManager.GetString("OnlyUseWith0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Weave.
        /// </summary>
        internal static string OnlyWeave {
            get {
                return ResourceManager.GetString("OnlyWeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only with countdown.
        /// </summary>
        internal static string OnlyWithCountdown {
            get {
                return ResourceManager.GetString("OnlyWithCountdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player HP% to be greater than or equal to:.
        /// </summary>
        internal static string PlayerHPGreaterOrEqual {
            get {
                return ResourceManager.GetString("PlayerHPGreaterOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player HP% to be less than or equal to:.
        /// </summary>
        internal static string PlayerHPLessOrEqual {
            get {
                return ResourceManager.GetString("PlayerHPLessOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player HP% to use {0} at or below.
        ///Set to 100 to disable this check..
        /// </summary>
        internal static string PlayerHPToUseAction {
            get {
                return ResourceManager.GetString("PlayerHPToUseAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player HP% to use {0} as extra tankbuster mitigation.  Set to 100 to disable this check.
        /// </summary>
        internal static string PlayerHPToUseExtraMitigation {
            get {
                return ResourceManager.GetString("PlayerHPToUseExtraMitigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are Off-Tanking, and want to use Sheltron on yourself:
        ///        - The expectation would be that you do so via the One-Button Mitigation Feature or the Mitigation options in your rotation.
        ///        - You could also mouseover yourself in the party to use Sheltron in this case.
        ///        - If you don&apos;t, intervention would replace the combo, and it would go to the main tank.
        ///        - If you don&apos;t use those Features for your personal mitigation, you may not want to enable this..
        /// </summary>
        internal static string PLDSheltronWarning {
            get {
                return ResourceManager.GetString("PLDSheltronWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prio buff upkeep.
        /// </summary>
        internal static string PrioBuffUpkeep {
            get {
                return ResourceManager.GetString("PrioBuffUpkeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prioritize {0} .
        /// </summary>
        internal static string Prioritize {
            get {
                return ResourceManager.GetString("Prioritize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority: .
        /// </summary>
        internal static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range Based Targeting.
        /// </summary>
        internal static string RangeBasedTargeting {
            get {
                return ResourceManager.GetString("RangeBasedTargeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose to retarget to the nearest of furthest enemy outside of 5y..
        /// </summary>
        internal static string RangeBasedTargetingDesc {
            get {
                return ResourceManager.GetString("RangeBasedTargetingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace {0} with {1} / {2}..
        /// </summary>
        internal static string Replace0With1Or2 {
            get {
                return ResourceManager.GetString("Replace0With1Or2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaces {0}.
        /// </summary>
        internal static string Replaces0 {
            get {
                return ResourceManager.GetString("Replaces0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires a Party to use..
        /// </summary>
        internal static string RequireParty {
            get {
                return ResourceManager.GetString("RequireParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires a battle target to start the opener..
        /// </summary>
        internal static string RequireTarget {
            get {
                return ResourceManager.GetString("RequireTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaces {0} with {1} to disable and prevent wasted use..
        /// </summary>
        internal static string SavageBladeWaste {
            get {
                return ResourceManager.GetString("SavageBladeWaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save {0} charges for burst..
        /// </summary>
        internal static string Save0ChargesForBurst {
            get {
                return ResourceManager.GetString("Save0ChargesForBurst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select what kind of content this option applies to:.
        /// </summary>
        internal static string SelectWhatKindOfContentThisOptionAppliesTo {
            get {
                return ResourceManager.GetString("SelectWhatKindOfContentThisOptionAppliesTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Only.
        /// </summary>
        internal static string SelfOnly {
            get {
                return ResourceManager.GetString("SelfOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield Check: Percentage of Party Members without shields to check for..
        /// </summary>
        internal static string ShieldCheckPartyMemberNeedPercent {
            get {
                return ResourceManager.GetString("ShieldCheckPartyMemberNeedPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Targeting.
        /// </summary>
        internal static string SmartTargeting {
            get {
                return ResourceManager.GetString("SmartTargeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest and Farthest Options will only target enemies not targeting the player..
        /// </summary>
        internal static string SmartTargetingNotTargetingPlayer {
            get {
                return ResourceManager.GetString("SmartTargetingNotTargetingPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft Target.
        /// </summary>
        internal static string SoftTarget {
            get {
                return ResourceManager.GetString("SoftTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard opener.
        /// </summary>
        internal static string StandardOpener {
            get {
                return ResourceManager.GetString("StandardOpener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start using when below party average HP %.
        ///Set to 100 to disable this check.
        /// </summary>
        internal static string StartUsingWhenBelowPartyAverageHPSetTo100ToDisableThisCheck {
            get {
                return ResourceManager.GetString("StartUsingWhenBelowPartyAverageHPSetTo100ToDisableThisCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stationary Delay Check (in seconds):.
        /// </summary>
        internal static string StationaryDelayCheck {
            get {
                return ResourceManager.GetString("StationaryDelayCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stationary Only.
        /// </summary>
        internal static string StationaryOnly {
            get {
                return ResourceManager.GetString("StationaryOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop using when average health percentage of nearby enemies is below set.
        ///(Set to 0 to disable this check).
        /// </summary>
        internal static string StopBelowAverageEnemyHP {
            get {
                return ResourceManager.GetString("StopBelowAverageEnemyHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop using when below Enemy HP %.
        ///Set to Zero to disable this check..
        /// </summary>
        internal static string StopEnemyHpPercent {
            get {
                return ResourceManager.GetString("StopEnemyHpPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start using when below HP %.
        ///Set to 100 to disable this check.
        /// </summary>
        internal static string StopFriendlyHpPercent100 {
            get {
                return ResourceManager.GetString("StopFriendlyHpPercent100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop using when below HP %.
        ///Set to Zero to disable this check.
        /// </summary>
        internal static string StopFriendlyHpPercentZero {
            get {
                return ResourceManager.GetString("StopFriendlyHpPercentZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds remaining before reapplying.
        ///(0 = Do not reapply early).
        /// </summary>
        internal static string StopSeconds {
            get {
                return ResourceManager.GetString("StopSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Using {0} When Target HP% is at or Below
        ///(Set to 0 to Disable This Check).
        /// </summary>
        internal static string StopUsing0WhenBelowTargetHPPercentage {
            get {
                return ResourceManager.GetString("StopUsing0WhenBelowTargetHPPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop using when below set percentage.
        /// </summary>
        internal static string StopUsingWhenBelowSetPercentage {
            get {
                return ResourceManager.GetString("StopUsingWhenBelowSetPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Using when Target HP% is at or Below
        ///(Set to 0 to Disable This Check).
        /// </summary>
        internal static string StopUsingWhenBelowTargetHPPercent {
            get {
                return ResourceManager.GetString("StopUsingWhenBelowTargetHPPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanks Only.
        /// </summary>
        internal static string TanksOnly {
            get {
                return ResourceManager.GetString("TanksOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target HP% to use {0} at or below.
        ///Set to 100 to disable this check..
        /// </summary>
        internal static string TargetHPUse0AtOrBelow {
            get {
                return ResourceManager.GetString("TargetHPUse0AtOrBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Remaining on {0} to allow within
        ///(0 = {0} must not be on the target).
        /// </summary>
        internal static string TimeRemainingOn0 {
            get {
                return ResourceManager.GetString("TimeRemainingOn0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Remaining on others {0} to allow within
        ///(0 = {0} must not be on the target).
        /// </summary>
        internal static string TimeRemainingOnOthers {
            get {
                return ResourceManager.GetString("TimeRemainingOnOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Remaining on others {0} / {1} / {2} to allow within
        ///(0 = {0} / {1} / {2} must not be on the target).
        /// </summary>
        internal static string TimeRemainingOnOthers3 {
            get {
                return ResourceManager.GetString("TimeRemainingOnOthers3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two target dotting.
        /// </summary>
        internal static string TwoTargetDotting {
            get {
                return ResourceManager.GetString("TwoTargetDotting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will maintain Damage over time spells on two targets if applicable..
        /// </summary>
        internal static string TwoTargetDottingDescription {
            get {
                return ResourceManager.GetString("TwoTargetDottingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {0} Opener.
        /// </summary>
        internal static string Use_0_Opener {
            get {
                return ResourceManager.GetString("Use_0_Opener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {0}.
        /// </summary>
        internal static string Use0 {
            get {
                return ResourceManager.GetString("Use0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {0} and {1}..
        /// </summary>
        internal static string Use0And1 {
            get {
                return ResourceManager.GetString("Use0And1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {0} before {1}.
        /// </summary>
        internal static string Use0Before1 {
            get {
                return ResourceManager.GetString("Use0Before1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {0} in {1}.
        /// </summary>
        internal static string Use0In1 {
            get {
                return ResourceManager.GetString("Use0In1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {0} / {1}.
        /// </summary>
        internal static string Use0Or1 {
            get {
                return ResourceManager.GetString("Use0Or1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {0} regardless of content..
        /// </summary>
        internal static string Use0RegardlessOfContent {
            get {
                return ResourceManager.GetString("Use0RegardlessOfContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {0} regardless of target..
        /// </summary>
        internal static string Use0RegardlessOfTarget {
            get {
                return ResourceManager.GetString("Use0RegardlessOfTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {0} when {1} charges are available..
        /// </summary>
        internal static string Use0When1ChargesAreAvailable {
            get {
                return ResourceManager.GetString("Use0When1ChargesAreAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {0} when in range of a selected enemy target..
        /// </summary>
        internal static string Use0WhenInRangeOfEnemy {
            get {
                return ResourceManager.GetString("Use0WhenInRangeOfEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {0} only while stationary.
        /// </summary>
        internal static string UseActionOnlyWhileStationary {
            get {
                return ResourceManager.GetString("UseActionOnlyWhileStationary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use always..
        /// </summary>
        internal static string UseAlways {
            get {
                return ResourceManager.GetString("UseAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses {0} regardless of any movement conditions.
        ///NOTE: This could possibly get you killed.
        /// </summary>
        internal static string Uses0RegardlessOfAnyMovementConditions {
            get {
                return ResourceManager.GetString("Uses0RegardlessOfAnyMovementConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses Standard opener.
        /// </summary>
        internal static string UsesStandardOpener {
            get {
                return ResourceManager.GetString("UsesStandardOpener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Use when Distance from target is greater than or equal to:.
        /// </summary>
        internal static string UseWhenDistanceFromTargetIsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("UseWhenDistanceFromTargetIsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Use when Distance from target is less than or equal to:.
        /// </summary>
        internal static string UseWhenDistanceFromTargetIsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("UseWhenDistanceFromTargetIsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste Prevention Option.
        /// </summary>
        internal static string WastePrevention {
            get {
                return ResourceManager.GetString("WastePrevention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will add {0} to the priority stack.
        /// </summary>
        internal static string WillAdd_0_ToThePriorityStack {
            get {
                return ResourceManager.GetString("WillAdd_0_ToThePriorityStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will not use in Boss encounters..
        /// </summary>
        internal static string WillNotUseInBossEncounters {
            get {
                return ResourceManager.GetString("WillNotUseInBossEncounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will only use on Tanks.
        /// </summary>
        internal static string WillOnlyUseOnTanks {
            get {
                return ResourceManager.GetString("WillOnlyUseOnTanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will only weave this action..
        /// </summary>
        internal static string WillOnlyWeaveThisAction {
            get {
                return ResourceManager.GetString("WillOnlyWeaveThisAction", resourceCulture);
            }
        }
    }
}
