//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrathCombo.Resources.Localization.JobConfigs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MCH_Config {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MCH_Config() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WrathCombo.Resources.Localization.JobConfigs.MCH_Config", typeof(MCH_Config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also use {0} / {1} on cooldown..
        /// </summary>
        internal static string AlsoUse0Or1OnCooldown {
            get {
                return ResourceManager.GetString("AlsoUse0Or1OnCooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery threshold.
        /// </summary>
        internal static string BatteryThreshold {
            get {
                return ResourceManager.GetString("BatteryThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes to {0} / {1} depending on charges and what was used last.
        /// </summary>
        internal static string ChangesTo0Or1 {
            get {
                return ResourceManager.GetString("ChangesTo0Or1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Early {0} opener.
        /// </summary>
        internal static string Early0Opener {
            get {
                return ResourceManager.GetString("Early0Opener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT RECOMMENDED!
        ///Only useful in Deep Dungeons to single pull.
        ///Will only work up until lvl 92..
        /// </summary>
        internal static string NotRecommended {
            get {
                return ResourceManager.GetString("NotRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves {0} for 2 minute windows
        ///THIS WILL CAUSE IT TO OVERCAP!.
        /// </summary>
        internal static string Save0ForEvenWindows {
            get {
                return ResourceManager.GetString("Save0ForEvenWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save for 2 minute windows.
        /// </summary>
        internal static string SaveForEvenWindows {
            get {
                return ResourceManager.GetString("SaveForEvenWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Using Tools When Target HP% is at or Below
        ///(Set to 0 to Disable This Check).
        /// </summary>
        internal static string StopUsingToolsBelowHpPercentage {
            get {
                return ResourceManager.GetString("StopUsingToolsBelowHpPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses {0} every minute/whenever your highest level tool is off cooldown..
        /// </summary>
        internal static string Use0EveryMinute {
            get {
                return ResourceManager.GetString("Use0EveryMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses Early {0} level 100 opener.
        /// </summary>
        internal static string UseEarly0Opener {
            get {
                return ResourceManager.GetString("UseEarly0Opener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use every minute.
        /// </summary>
        internal static string UseEveryMinute {
            get {
                return ResourceManager.GetString("UseEveryMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {0} at this battery threshold outside of Boss encounter..
        /// </summary>
        internal static string UseQueenOutsideOfBoss {
            get {
                return ResourceManager.GetString("UseQueenOutsideOfBoss", resourceCulture);
            }
        }
    }
}
