//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrathCombo.Resources.Localization.JobConfigs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RDM_Config {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RDM_Config() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WrathCombo.Resources.Localization.JobConfigs.RDM_Config", typeof(RDM_Config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0}/{1} Finishers.
        /// </summary>
        internal static string Add0_1Finishers {
            get {
                return ResourceManager.GetString("Add0/1Finishers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: {0} IS NOT ENABLED..
        /// </summary>
        internal static string AutoRotationWarning1 {
            get {
                return ResourceManager.GetString("AutoRotationWarning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTO ROTATION WILL NOT START THE MELEE COMBO AUTOMATICALLY.
        /// </summary>
        internal static string AutoRotationWarning2 {
            get {
                return ResourceManager.GetString("AutoRotationWarning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamically switch to {0}.
        /// </summary>
        internal static string DynamicallySwitchTo0 {
            get {
                return ResourceManager.GetString("DynamicallySwitchTo0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull with {0}/{1}.
        /// </summary>
        internal static string PullWith0_1 {
            get {
                return ResourceManager.GetString("PullWith0/1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gap-Closing Adjusted Standard Opener.
        /// </summary>
        internal static string RDMGapCloserOpener {
            get {
                return ResourceManager.GetString("RDMGapCloserOpener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opener Failure Timeout (in Settings Tab) Must be set to 5+ seconds for opener to function due to long initial spell cast..
        /// </summary>
        internal static string RDMOpenerTimeoutWarning {
            get {
                return ResourceManager.GetString("RDMOpenerTimeoutWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opener Failure Timeout (in Settings Tab) Must be set to 5+ seconds for opener to function due to long initial spell cast..
        /// </summary>
        internal static string RDMOpenerWarning {
            get {
                return ResourceManager.GetString("RDMOpenerWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts with {0}/{1} if out of combat..
        /// </summary>
        internal static string StartsWith0_1 {
            get {
                return ResourceManager.GetString("StartsWith0/1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switches to {0} if black mana is lower..
        /// </summary>
        internal static string SwitchToBlack {
            get {
                return ResourceManager.GetString("SwitchToBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switches to {0} if white mana is lower..
        /// </summary>
        internal static string SwitchToWhite {
            get {
                return ResourceManager.GetString("SwitchToWhite", resourceCulture);
            }
        }
    }
}
