//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrathCombo.Resources.Localization.JobConfigs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RPR_Config {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RPR_Config() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WrathCombo.Resources.Localization.JobConfigs.RPR_Config", typeof(RPR_Config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First positional: {0}..
        /// </summary>
        internal static string FirstPositional0 {
            get {
                return ResourceManager.GetString("FirstPositional0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flank First.
        /// </summary>
        internal static string FlankFirst {
            get {
                return ResourceManager.GetString("FlankFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string On0 {
            get {
                return ResourceManager.GetString("On0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only uses {0} while you have {1}..
        /// </summary>
        internal static string OnlyUse0WhileUGot1 {
            get {
                return ResourceManager.GetString("OnlyUse0WhileUGot1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rear First.
        /// </summary>
        internal static string RearFirst {
            get {
                return ResourceManager.GetString("RearFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds remaining before refreshing {0}.
        ///Recommended is 6..
        /// </summary>
        internal static string SecondsBeforeRefreshing0 {
            get {
                return ResourceManager.GetString("SecondsBeforeRefreshing0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will hold the last charge of {0} for use with {1}, even when out of position for {2}/{3}.
        ///If above slider is set to 1, it will NOT use the remaining charge for {1}, but for manual use..
        /// </summary>
        internal static string WillHoldTNforGluttony {
            get {
                return ResourceManager.GetString("WillHoldTNforGluttony", resourceCulture);
            }
        }
    }
}
