//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrathCombo.Resources.Localization.JobConfigs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SGE_Config {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SGE_Config() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WrathCombo.Resources.Localization.JobConfigs.SGE_Config", typeof(SGE_Config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any {0} check.
        /// </summary>
        internal static string AnyPanhaimaCheck {
            get {
                return ResourceManager.GetString("AnyPanhaimaCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable to not override an existing {0}..
        /// </summary>
        internal static string AnyPanhaimaCheckDesc {
            get {
                return ResourceManager.GetString("AnyPanhaimaCheckDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for {0} Trait (Heal over Time).
        /// </summary>
        internal static string KerecholeTraitCheck {
            get {
                return ResourceManager.GetString("KerecholeTraitCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling this will prevent {0} from being used when the Heal over Time trait is unavailable..
        /// </summary>
        internal static string KerecholeTraitCheckDesc {
            get {
                return ResourceManager.GetString("KerecholeTraitCheckDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will add {0} at beginning.
        /// </summary>
        internal static string SGE_Mit_AoE_Kerachole_Help {
            get {
                return ResourceManager.GetString("SGE_Mit_AoE_Kerachole_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will add {0} at the end.
        /// </summary>
        internal static string SGE_Mit_AoE_Panhaima_Help {
            get {
                return ResourceManager.GetString("SGE_Mit_AoE_Panhaima_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will add {0} before {1} for the Healing Boost.
        /// </summary>
        internal static string SGE_Mit_AoE_Philosophia_Help {
            get {
                return ResourceManager.GetString("SGE_Mit_AoE_Philosophia_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield Check: Percentage of Party Members to get {0} shields. 
        ///0 = Dont use, 100 = everyone needs shields.
        /// </summary>
        internal static string SGE_Mit_AoE_PrognosisOption_Name {
            get {
                return ResourceManager.GetString("SGE_Mit_AoE_PrognosisOption_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will add {0} for more mitigation..
        /// </summary>
        internal static string SGE_Mit_ST_Haima_Help {
            get {
                return ResourceManager.GetString("SGE_Mit_ST_Haima_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will add {0} to top off targets health and add Damage reduction..
        /// </summary>
        internal static string SGE_Mit_ST_Taurochole_Help {
            get {
                return ResourceManager.GetString("SGE_Mit_ST_Taurochole_Help", resourceCulture);
            }
        }
    }
}
