//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrathCombo.Resources.Localization.JobConfigs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VPR_Config {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VPR_Config() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WrathCombo.Resources.Localization.JobConfigs.VPR_Config", typeof(VPR_Config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds {0} when available.
        /// Respects the manual {0} charge..
        /// </summary>
        internal static string Add0WhenAvailableRespectManualCharge {
            get {
                return ResourceManager.GetString("Add0WhenAvailableRespectManualCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds range check for {0}, so it is used only when in range..
        /// </summary>
        internal static string AddRangeCheckFor0 {
            get {
                return ResourceManager.GetString("AddRangeCheckFor0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds range check for {0} and {1}, so it is used only when in range..
        /// </summary>
        internal static string AddRangeCheckFor0And1 {
            get {
                return ResourceManager.GetString("AddRangeCheckFor0And1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables the range check for {0}, so it will be used even without a target selected..
        /// </summary>
        internal static string DisableRangeCheckFor0 {
            get {
                return ResourceManager.GetString("DisableRangeCheckFor0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables the range check for {0} and {1}, so it will be used even without a target selected..
        /// </summary>
        internal static string DisableRangeCheckFor0And1 {
            get {
                return ResourceManager.GetString("DisableRangeCheckFor0And1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forces {0} or {1} if buff needs to be reapplied..
        /// </summary>
        internal static string Forces0Or1ForBuffs {
            get {
                return ResourceManager.GetString("Forces0Or1ForBuffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a HP% threshold to use {0} whenever available. (Bosses Only).
        /// </summary>
        internal static string HPPThresholdWheneverAvailableBossesOnly {
            get {
                return ResourceManager.GetString("HPPThresholdWheneverAvailableBossesOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaces {0} with Full Generation - Legacy combo..
        /// </summary>
        internal static string Replace0WithFullCombo {
            get {
                return ResourceManager.GetString("Replace0WithFullCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will hold the last charge of {0} for use with {1}, even when out of position for normal GCD.
        ///If above slider is set to 1, it will NOT use the remaining charge for {1}, but for manual use..
        /// </summary>
        internal static string WillHoldLastChargeOf0For1 {
            get {
                return ResourceManager.GetString("WillHoldLastChargeOf0For1", resourceCulture);
            }
        }
    }
}
