//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrathCombo.Resources.Localization.UI.Features {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FeaturesUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeaturesUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WrathCombo.Resources.Localization.UI.Features.FeaturesUI", typeof(FeaturesUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Button_Back {
            get {
                return ResourceManager.GetString("Button_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptions.
        /// </summary>
        internal static string Checkbox_searchDescriptionText {
            get {
                return ResourceManager.GetString("Checkbox_searchDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add this feature to Auto-Rotation.
        ///Auto-Rotation will automatically use the actions selected within the feature, allowing you to focus on movement. Configure the settings in the &apos;Auto-Rotation&apos; section..
        /// </summary>
        internal static string Hover_AutoMode {
            get {
                return ResourceManager.GetString("Hover_AutoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The setting that controls if this action is retargeted is:.
        /// </summary>
        internal static string Hover_Retargetting_ControllingSetting {
            get {
                return ResourceManager.GetString("Hover_Retargetting_ControllingSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Feature&apos;s actions are retargeted.
        /// </summary>
        internal static string Hover_Retargetting_IsRetargetted {
            get {
                return ResourceManager.GetString("Hover_Retargetting_IsRetargetted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The actions from this Feature will automatically be
        ///targeted onto what the developers feel is the best target
        ///(following The Balance where applicable)..
        /// </summary>
        internal static string Hover_Retargetting_Line2 {
            get {
                return ResourceManager.GetString("Hover_Retargetting_Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using plugins like Redirect or Reaction with configurations
        ///affecting this action will Conflict and may cause issues..
        /// </summary>
        internal static string Hover_Retargetting_Line3 {
            get {
                return ResourceManager.GetString("Hover_Retargetting_Line3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Feature&apos;s actions may be retargeted..
        /// </summary>
        internal static string Hover_Retargetting_MaybeRetargetted {
            get {
                return ResourceManager.GetString("Hover_Retargetting_MaybeRetargetted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All required spells active!.
        /// </summary>
        internal static string Info_BLUAllGoodSpells {
            get {
                return ResourceManager.GetString("Info_BLUAllGoodSpells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Replacing is Disabled in Settings! PvP Combos will not work!.
        /// </summary>
        internal static string Info_pvpActionReplacingWarning {
            get {
                return ResourceManager.GetString("Info_pvpActionReplacingWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Rotation is unavailable for PvP..
        /// </summary>
        internal static string Info_pvpAutoRotationWarning {
            get {
                return ResourceManager.GetString("Info_pvpAutoRotationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are PvP features. They will only work in PvP-enabled zones..
        /// </summary>
        internal static string Info_pvpDesc {
            get {
                return ResourceManager.GetString("Info_pvpDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing matched your search..
        /// </summary>
        internal static string Info_pvpNothing {
            get {
                return ResourceManager.GetString("Info_pvpNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a job from below to enable and configure features for it..
        /// </summary>
        internal static string Info_SelectAJob {
            get {
                return ResourceManager.GetString("Info_SelectAJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Mode.
        /// </summary>
        internal static string Label_AutoMode {
            get {
                return ResourceManager.GetString("Label_AutoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicts with:.
        /// </summary>
        internal static string Label_ConflictsWith {
            get {
                return ResourceManager.GetString("Label_ConflictsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        internal static string Label_searchLabelText {
            get {
                return ResourceManager.GetString("Label_searchLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option name, ID, Internal Name, Description, etc.
        /// </summary>
        internal static string Search_searchHintText {
            get {
                return ResourceManager.GetString("Search_searchHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing active spells:.
        /// </summary>
        internal static string Warning_BLUMissingSpells {
            get {
                return ResourceManager.GetString("Warning_BLUMissingSpells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Required Spells Active:.
        /// </summary>
        internal static string Warning_BLUNoSpells {
            get {
                return ResourceManager.GetString("Warning_BLUNoSpells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled due to update.
        /// </summary>
        internal static string Warning_DisabledDueToUpdate {
            get {
                return ResourceManager.GetString("Warning_DisabledDueToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip your job stone to re-unlock features..
        /// </summary>
        internal static string Warning_EquipJobStone {
            get {
                return ResourceManager.GetString("Warning_EquipJobStone", resourceCulture);
            }
        }
    }
}
