//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrathCombo.Resources.Localization.Content {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OccultCrescent {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OccultCrescent() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WrathCombo.Resources.Localization.Content.OccultCrescent", typeof(OccultCrescent).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0} or {1} prior to using {2}.
        /// </summary>
        internal static string Add0Or1PriorUsing2 {
            get {
                return ResourceManager.GetString("Add0Or1PriorUsing2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require at least 1 party member.
        /// </summary>
        internal static string AtLeast1PartyMember {
            get {
                return ResourceManager.GetString("AtLeast1PartyMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg Party HP to be less than or equal to:.
        /// </summary>
        internal static string AveragePartyHPLessOrEqual {
            get {
                return ResourceManager.GetString("AveragePartyHPLessOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are NOT one of the jobs that regularly damage buffs themselves, or do not party up in OC, then this will SKIP using Phantom Abilities until burst time is detected (which might be never on a buff-less job)!.
        /// </summary>
        internal static string BuffOnlyDont {
            get {
                return ResourceManager.GetString("BuffOnlyDont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRK, PLD, WAR, AST, MNK, DRG, NIN, BRD, are the only jobs this is likely to be a good option for.
        /// </summary>
        internal static string BuffOnlyList {
            get {
                return ResourceManager.GetString("BuffOnlyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many jobs do not have self buffs that are up regularly, many burst phases cannot accommodate extra Phantom Abilities, and many Phantom Abilities are up more often than this on would be on many jobs!.
        /// </summary>
        internal static string BuffOnlyNotRecommended {
            get {
                return ResourceManager.GetString("BuffOnlyNotRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a costly Feature!.
        /// </summary>
        internal static string Costly {
            get {
                return ResourceManager.GetString("Costly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not advisable in most situations!.
        /// </summary>
        internal static string NotAdvised {
            get {
                return ResourceManager.GetString("NotAdvised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require {0} or {1} to use {2}.
        /// </summary>
        internal static string Requires0Or1ToUse2 {
            get {
                return ResourceManager.GetString("Requires0Or1ToUse2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The slider value should be rather low, if you do use it!.
        /// </summary>
        internal static string SliderShouldBeLow {
            get {
                return ResourceManager.GetString("SliderShouldBeLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a VERY costly Feature!.
        /// </summary>
        internal static string VeryCostly {
            get {
                return ResourceManager.GetString("VeryCostly", resourceCulture);
            }
        }
    }
}
