//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrathCombo.Resources.Localization.UI.Settings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsCfgUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsCfgUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WrathCombo.Resources.Localization.UI.Settings.SettingsCfgUI", typeof(SettingsCfgUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string ActionChanging_defaultValue {
            get {
                return ResourceManager.GetString("ActionChanging_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether Actions on your Hotbar will be Replaced with combos from the plugin.
        ///If disabled, your manual presses of abilities will no longer be affected by any QoL Tweaks settings.
        ///
        ///Auto-Rotation will work regardless of the setting..
        /// </summary>
        internal static string ActionChanging_helpMark {
            get {
                return ResourceManager.GetString("ActionChanging_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Replacing.
        /// </summary>
        internal static string ActionChanging_Name {
            get {
                return ResourceManager.GetString("ActionChanging_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On (This is essentially turning OFF most of QoL Tweaks).
        /// </summary>
        internal static string ActionChanging_recommendedValue {
            get {
                return ResourceManager.GetString("ActionChanging_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QoL Tweaks is largely designed with Action Replacing in mind.
        ///Only Auto-Rotation will work if this is disabled.
        ///Disabling it may also lead to unexpected behavior, such as regarding Retargeting..
        /// </summary>
        internal static string ActionChanging_warningMark {
            get {
                return ResourceManager.GetString("ActionChanging_warningMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string AddOutOfPartyNPCsToRetargeting_defaultValue {
            get {
                return ResourceManager.GetString("AddOutOfPartyNPCsToRetargeting_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will add any NPCs that are not in your party to the retargeting logic for healing actions.
        ///
        ///Useful for healers who want to be able to target NPCs that are not in their party, such as quest NPCs.
        ///These NPCs will not generally work with any role-based custom Heal Stack entries
        ///(even if an NPC looks like a tank, they&apos;re not always classified as one).
        /// </summary>
        internal static string AddOutOfPartyNPCsToRetargeting_helpMark {
            get {
                return ResourceManager.GetString("AddOutOfPartyNPCsToRetargeting_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Out-of-Party NPCs to Retargeting.
        /// </summary>
        internal static string AddOutOfPartyNPCsToRetargeting_Name {
            get {
                return ResourceManager.GetString("AddOutOfPartyNPCsToRetargeting_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On (If you use Retargeting at all).
        /// </summary>
        internal static string AddOutOfPartyNPCsToRetargeting_recommendedValue {
            get {
                return ResourceManager.GetString("AddOutOfPartyNPCsToRetargeting_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string AoEDamageToast_defaultValue {
            get {
                return ResourceManager.GetString("AoEDamageToast_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show a message on-screen whenever a stack/group damage cast is detected, including who it is targeting if applicable..
        /// </summary>
        internal static string AoEDamageToast_helpMark {
            get {
                return ResourceManager.GetString("AoEDamageToast_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Toast on Group Damage.
        /// </summary>
        internal static string AoEDamageToast_Name {
            get {
                return ResourceManager.GetString("AoEDamageToast_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        internal static string AoEDamageToast_recommendedValue {
            get {
                return ResourceManager.GetString("AoEDamageToast_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string AoEDamageTTS_defaultValue {
            get {
                return ResourceManager.GetString("AoEDamageTTS_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will play a text-to-speech sound clip whenever a stack/group damage cast is detected, including who it is targeting if applicable..
        /// </summary>
        internal static string AoEDamageTTS_helpMark {
            get {
                return ResourceManager.GetString("AoEDamageTTS_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play TTS on Group Damage.
        /// </summary>
        internal static string AoEDamageTTS_Name {
            get {
                return ResourceManager.GetString("AoEDamageTTS_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        internal static string AoEDamageTTS_recommendedValue {
            get {
                return ResourceManager.GetString("AoEDamageTTS_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On, cause it&apos;s that type of day y&apos;know.
        /// </summary>
        internal static string AprilFools2026_defaultValue {
            get {
                return ResourceManager.GetString("AprilFools2026_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For when you can&apos;t get enough MNK in your plugin..
        /// </summary>
        internal static string AprilFools2026_helpMark {
            get {
                return ResourceManager.GetString("AprilFools2026_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April Fools 2026 Feature.
        /// </summary>
        internal static string AprilFools2026_Name {
            get {
                return ResourceManager.GetString("AprilFools2026_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off, unless your name starts with Beep.
        /// </summary>
        internal static string AprilFools2026_recommendedValue {
            get {
                return ResourceManager.GetString("AprilFools2026_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string BlockSpellOnMove_defaultValue {
            get {
                return ResourceManager.GetString("BlockSpellOnMove_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will completely block actions while moving, by replacing Combo outputs with Savage Blade.
        ///This would supersede combo-specific movement options, which many jobs have..
        /// </summary>
        internal static string BlockSpellOnMove_helpMark {
            get {
                return ResourceManager.GetString("BlockSpellOnMove_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Spells while Moving.
        /// </summary>
        internal static string BlockSpellOnMove_Name {
            get {
                return ResourceManager.GetString("BlockSpellOnMove_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off (Most Jobs will handle this better with their Features).
        /// </summary>
        internal static string BlockSpellOnMove_recommendedValue {
            get {
                return ResourceManager.GetString("BlockSpellOnMove_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus Target &gt; Hard Target &gt; Self.
        /// </summary>
        internal static string CustomHealStack_defaultValue {
            get {
                return ResourceManager.GetString("CustomHealStack_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If there are fewer than 4 items, and all return nothing when checked, will fall back to Self.
        ///
        ///These targets will only be considered valid if they are friendly and within 25y.
        ///
        ///When applied to something like Esuna, these targets will be checked for having a Cleansable Debuff, etc.
        ///So adding &apos;Any Cleansable Ally&apos; or similar is not necessary..
        /// </summary>
        internal static string CustomHealStack_helpMark {
            get {
                return ResourceManager.GetString("CustomHealStack_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Heal Stack.
        /// </summary>
        internal static string CustomHealStack_Name {
            get {
                return ResourceManager.GetString("CustomHealStack_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        internal static string CustomHealStack_recommendedValue {
            get {
                return ResourceManager.GetString("CustomHealStack_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string EnabledOutputLog_defaultValue {
            get {
                return ResourceManager.GetString("EnabledOutputLog_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will print to chat every time you use an action provided by QoL Tweaks..
        /// </summary>
        internal static string EnabledOutputLog_helpMark {
            get {
                return ResourceManager.GetString("EnabledOutputLog_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Log to Chat.
        /// </summary>
        internal static string EnabledOutputLog_Name {
            get {
                return ResourceManager.GetString("EnabledOutputLog_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On (IF trying to report an issue).
        /// </summary>
        internal static string EnabledOutputLog_recommendedValue {
            get {
                return ResourceManager.GetString("EnabledOutputLog_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string HideChildren_defaultValue {
            get {
                return ResourceManager.GetString("HideChildren_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will hide the Features and Options under disabled Combos..
        /// </summary>
        internal static string HideChildren_helpMark {
            get {
                return ResourceManager.GetString("HideChildren_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Sub-Combo Options.
        /// </summary>
        internal static string HideChildren_Name {
            get {
                return ResourceManager.GetString("HideChildren_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        internal static string HideChildren_recommendedValue {
            get {
                return ResourceManager.GetString("HideChildren_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string HideConflictedCombos_defaultValue {
            get {
                return ResourceManager.GetString("HideConflictedCombos_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will hide Combos that conflict with Combos that you have enabled..
        /// </summary>
        internal static string HideConflictedCombos_helpMark {
            get {
                return ResourceManager.GetString("HideConflictedCombos_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Conflicted Combos.
        /// </summary>
        internal static string HideConflictedCombos_Name {
            get {
                return ResourceManager.GetString("HideConflictedCombos_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        internal static string HideConflictedCombos_recommendedValue {
            get {
                return ResourceManager.GetString("HideConflictedCombos_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string HideMessageOfTheDay_defaultValue {
            get {
                return ResourceManager.GetString("HideMessageOfTheDay_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will prevent the Message of the Day from being shown in your chat upon login..
        /// </summary>
        internal static string HideMessageOfTheDay_helpMark {
            get {
                return ResourceManager.GetString("HideMessageOfTheDay_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Message of the Day.
        /// </summary>
        internal static string HideMessageOfTheDay_Name {
            get {
                return ResourceManager.GetString("HideMessageOfTheDay_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        internal static string HideMessageOfTheDay_recommendedValue {
            get {
                return ResourceManager.GetString("HideMessageOfTheDay_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string InterruptDelay_defaultValue {
            get {
                return ResourceManager.GetString("InterruptDelay_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the percentage of a total cast time to wait before interrupting enemy casts.
        ///Applies to all interrupts (including stuns used to interrupt) in every Job&apos;s Combos..
        /// </summary>
        internal static string InterruptDelay_helpMark {
            get {
                return ResourceManager.GetString("InterruptDelay_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interrupt Delay.
        /// </summary>
        internal static string InterruptDelay_Name {
            get {
                return ResourceManager.GetString("InterruptDelay_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to below 40 (Above that and you start failing to interrupt many short casts).
        /// </summary>
        internal static string InterruptDelay_recommendedValue {
            get {
                return ResourceManager.GetString("InterruptDelay_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of cast.
        /// </summary>
        internal static string InterruptDelay_unitLabel {
            get {
                return ResourceManager.GetString("InterruptDelay_unitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main UI Options.
        /// </summary>
        internal static string MainUIOptions_Category {
            get {
                return ResourceManager.GetString("MainUIOptions_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string MaximumWeavesPerWindow_defaultValue {
            get {
                return ResourceManager.GetString("MaximumWeavesPerWindow_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how many oGCDs are allowed between GCDs.
        ///The &apos;default&apos; for the game is double weaving, but triple weaving is completely possible with low enough latency (of every kind);but if you struggle with latency of any sort then single weaving may even be a good answer to try for you.
        ///Triple weaving is already done in a manner where we try to avoid clipping GCDs, and as such doesn&apos;t happen particularly often even if you have good latency, and is a valid thing to do, so it is a safe option if you want..
        /// </summary>
        internal static string MaximumWeavesPerWindow_helpMark {
            get {
                return ResourceManager.GetString("MaximumWeavesPerWindow_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Number of Weaves.
        /// </summary>
        internal static string MaximumWeavesPerWindow_Name {
            get {
                return ResourceManager.GetString("MaximumWeavesPerWindow_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-3.
        /// </summary>
        internal static string MaximumWeavesPerWindow_recommendedValue {
            get {
                return ResourceManager.GetString("MaximumWeavesPerWindow_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of oGCDs.
        /// </summary>
        internal static string MaximumWeavesPerWindow_unitLabel {
            get {
                return ResourceManager.GetString("MaximumWeavesPerWindow_unitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string MeleeOffset_defaultValue {
            get {
                return ResourceManager.GetString("MeleeOffset_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls what is considered to be in melee range.
        ///Mainly for those who don&apos;t want to switch to ranged attacks if the boss walks slightly outside of range.
        ///For example a value of -0.5 would make you have to be 0.5 yalms closer to the target,
        ///or a value of 2 would allow you to be 2 yalms further away and still be considered in melee range
        ///(melee actions wouldn&apos;t work, but it would give you some warning instead of just suddenly doing less optimal actions)..
        /// </summary>
        internal static string MeleeOffset_helpMark {
            get {
                return ResourceManager.GetString("MeleeOffset_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee Distance Offset.
        /// </summary>
        internal static string MeleeOffset_Name {
            get {
                return ResourceManager.GetString("MeleeOffset_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string MeleeOffset_recommendedValue {
            get {
                return ResourceManager.GetString("MeleeOffset_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yalms.
        /// </summary>
        internal static string MeleeOffset_unitLabel {
            get {
                return ResourceManager.GetString("MeleeOffset_unitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string MovementLeeway_defaultValue {
            get {
                return ResourceManager.GetString("MovementLeeway_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This controls how long of a delay is needed before QoL Tweaks recognizes you as moving.
        ///This allows you to not have to worry about small movements affecting your rotation, primarily for casters..
        /// </summary>
        internal static string MovementLeeway_helpMark {
            get {
                return ResourceManager.GetString("MovementLeeway_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement Check Delay.
        /// </summary>
        internal static string MovementLeeway_Name {
            get {
                return ResourceManager.GetString("MovementLeeway_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.0-1.0 (Above that gets into the territory of breaking any Movement Options in your Job).
        /// </summary>
        internal static string MovementLeeway_recommendedValue {
            get {
                return ResourceManager.GetString("MovementLeeway_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string MovementLeeway_unitLabel {
            get {
                return ResourceManager.GetString("MovementLeeway_unitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string OpenerTimeout_defaultValue {
            get {
                return ResourceManager.GetString("OpenerTimeout_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how long of a gap with no action is allowed in an Opener, before it is considered failed and normal rotation is resumed.
        ///Can be necessary for some casters to increase, particularly when the first action of an Opener is a hard-cast..
        /// </summary>
        internal static string OpenerTimeout_helpMark {
            get {
                return ResourceManager.GetString("OpenerTimeout_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opener Failure Timeout.
        /// </summary>
        internal static string OpenerTimeout_Name {
            get {
                return ResourceManager.GetString("OpenerTimeout_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.0-7.0 (Above that can really screw Openers).
        /// </summary>
        internal static string OpenerTimeout_recommendedValue {
            get {
                return ResourceManager.GetString("OpenerTimeout_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string OpenerTimeout_unitLabel {
            get {
                return ResourceManager.GetString("OpenerTimeout_unitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string OpenToCurrentJob_defaultValue {
            get {
                return ResourceManager.GetString("OpenToCurrentJob_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the PvE Features tab is opened it will automatically open to your current Job..
        /// </summary>
        internal static string OpenToCurrentJob_helpMark {
            get {
                return ResourceManager.GetString("OpenToCurrentJob_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open PvE Features Tab to Current Job on Opening.
        /// </summary>
        internal static string OpenToCurrentJob_Name {
            get {
                return ResourceManager.GetString("OpenToCurrentJob_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        internal static string OpenToCurrentJob_recommendedValue {
            get {
                return ResourceManager.GetString("OpenToCurrentJob_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string OpenToCurrentJobOnSwitch_defaultValue {
            get {
                return ResourceManager.GetString("OpenToCurrentJobOnSwitch_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will automatically switch the PvE Features tab to the job you are currently playing, when you switch jobs..
        /// </summary>
        internal static string OpenToCurrentJobOnSwitch_helpMark {
            get {
                return ResourceManager.GetString("OpenToCurrentJobOnSwitch_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open PvE Features Tab to Current Job on Switching Jobs.
        /// </summary>
        internal static string OpenToCurrentJobOnSwitch_Name {
            get {
                return ResourceManager.GetString("OpenToCurrentJobOnSwitch_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        internal static string OpenToCurrentJobOnSwitch_recommendedValue {
            get {
                return ResourceManager.GetString("OpenToCurrentJobOnSwitch_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string OpenToPvE_defaultValue {
            get {
                return ResourceManager.GetString("OpenToPvE_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you open QoL Tweaks with `/qoltweaks`, it will open to the PvE Features tab, instead of the last tab you were on.
        ///Same as always using the `/qoltweaks pve` command to open QoL Tweaks..
        /// </summary>
        internal static string OpenToPvE_helpMark {
            get {
                return ResourceManager.GetString("OpenToPvE_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open QoL Tweaks to the PvE Features Tab.
        /// </summary>
        internal static string OpenToPvE_Name {
            get {
                return ResourceManager.GetString("OpenToPvE_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        internal static string OpenToPvE_recommendedValue {
            get {
                return ResourceManager.GetString("OpenToPvE_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string OpenToPvP_defaultValue {
            get {
                return ResourceManager.GetString("OpenToPvP_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same as above, when you open QoL Tweaks with `/qoltweaks`, it will open to the PvP Features tab, instead of the last tab you were on, when in a PvP area.
        ///Similar to using the `/qoltweaks pvp` command to open QoL Tweaks..
        /// </summary>
        internal static string OpenToPvP_helpMark {
            get {
                return ResourceManager.GetString("OpenToPvP_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open QoL Tweaks to the PvP Features Tab in PvP areas.
        /// </summary>
        internal static string OpenToPvP_Name {
            get {
                return ResourceManager.GetString("OpenToPvP_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        internal static string OpenToPvP_recommendedValue {
            get {
                return ResourceManager.GetString("OpenToPvP_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string OutputOpenerLogs_defaultValue {
            get {
                return ResourceManager.GetString("OutputOpenerLogs_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will print the status of your Job&apos;s Opener to chat.
        ///e.g. When it is Ready, Fails, or Finishes..
        /// </summary>
        internal static string OutputOpenerLogs_helpMark {
            get {
                return ResourceManager.GetString("OutputOpenerLogs_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Opener Status to Chat.
        /// </summary>
        internal static string OutputOpenerLogs_Name {
            get {
                return ResourceManager.GetString("OutputOpenerLogs_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On (IF trying to troubleshoot an Opener).
        /// </summary>
        internal static string OutputOpenerLogs_recommendedValue {
            get {
                return ResourceManager.GetString("OutputOpenerLogs_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string OverwriteQueue_defaultValue {
            get {
                return ResourceManager.GetString("OverwriteQueue_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will allow you to overwrite whatever is currently queued up with another action..
        /// </summary>
        internal static string OverwriteQueue_helpMark {
            get {
                return ResourceManager.GetString("OverwriteQueue_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite Queue.
        /// </summary>
        internal static string OverwriteQueue_Name {
            get {
                return ResourceManager.GetString("OverwriteQueue_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string OverwriteQueue_recommendedValue {
            get {
                return ResourceManager.GetString("OverwriteQueue_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string QueueAdjust_defaultValue {
            get {
                return ResourceManager.GetString("QueueAdjust_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows you to adjust your queue window to any time during the GCD rather than just within the last 0.3-0.5s. Useful if you&apos;re not mashing the key or using Auto-Rotation and wish to manually intervene..
        /// </summary>
        internal static string QueueAdjust_helpMark {
            get {
                return ResourceManager.GetString("QueueAdjust_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Manual Queue Window.
        /// </summary>
        internal static string QueueAdjust_Name {
            get {
                return ResourceManager.GetString("QueueAdjust_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string QueueAdjust_recommendedValue {
            get {
                return ResourceManager.GetString("QueueAdjust_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.5.
        /// </summary>
        internal static string QueueAdjustThreshold_defaultValue {
            get {
                return ResourceManager.GetString("QueueAdjustThreshold_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will allow you to queue when the GCD is at this time or less..
        /// </summary>
        internal static string QueueAdjustThreshold_helpMark {
            get {
                return ResourceManager.GetString("QueueAdjustThreshold_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Queueing At.
        /// </summary>
        internal static string QueueAdjustThreshold_Name {
            get {
                return ResourceManager.GetString("QueueAdjustThreshold_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.5-2.5.
        /// </summary>
        internal static string QueueAdjustThreshold_recommendedValue {
            get {
                return ResourceManager.GetString("QueueAdjustThreshold_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string QueueAdjustThreshold_unitLabel {
            get {
                return ResourceManager.GetString("QueueAdjustThreshold_unitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting this too low or to zero will make it really hard to manually queue..
        /// </summary>
        internal static string QueueAdjustThreshold_warningMark {
            get {
                return ResourceManager.GetString("QueueAdjustThreshold_warningMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Healer &gt; Any Tank &gt; Any Raiser &gt; Any Dead Party Member.
        /// </summary>
        internal static string RaiseStack_defaultValue {
            get {
                return ResourceManager.GetString("RaiseStack_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (all targets are checked for rezz-ability).
        /// </summary>
        internal static string RaiseStack_extraText {
            get {
                return ResourceManager.GetString("RaiseStack_extraText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the order in which QoL Tweaks will try to select a target to Raise,
        ///if Retargeting of any Raise Feature is enabled.
        ///
        ///You can find Raise Features under PvE&gt;General,
        ///or under each caster that has a Raise.
        ///
        ///If there are fewer than 5 items, and all return nothing when checked, will fall back to:
        ///your Hard Target if they&apos;re dead, or &lt;Any Dead Party Member&gt;.
        ///
        ///These targets will only be considered valid if they are friendly, dead, and within 30y..
        /// </summary>
        internal static string RaiseStack_helpMark {
            get {
                return ResourceManager.GetString("RaiseStack_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Raise Stack.
        /// </summary>
        internal static string RaiseStack_Name {
            get {
                return ResourceManager.GetString("RaiseStack_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        internal static string RaiseStack_recommendedValue {
            get {
                return ResourceManager.GetString("RaiseStack_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string RetargetHealingActionsToStack_defaultValue {
            get {
                return ResourceManager.GetString("RetargetHealingActionsToStack_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will Retarget all Single-Target Healing Actions to the Heal Stack as shown below,
        ///similarly to how Redirect or Reaction would.
        ///This ensures that the target used to check HP% threshold logic for healing actions is the same target that will receive that heal..
        /// </summary>
        internal static string RetargetHealingActionsToStack_helpMark {
            get {
                return ResourceManager.GetString("RetargetHealingActionsToStack_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retarget (Single Target) Healing Actions.
        /// </summary>
        internal static string RetargetHealingActionsToStack_Name {
            get {
                return ResourceManager.GetString("RetargetHealingActionsToStack_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On (If you customize the Heal Stack AT ALL).
        /// </summary>
        internal static string RetargetHealingActionsToStack_recommendedValue {
            get {
                return ResourceManager.GetString("RetargetHealingActionsToStack_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation Behaviour Options.
        /// </summary>
        internal static string RotationBehaviourOptions_Category {
            get {
                return ResourceManager.GetString("RotationBehaviourOptions_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string ShortDTRText_defaultValue {
            get {
                return ResourceManager.GetString("ShortDTRText_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will hide the number of active Auto-Mode Combos.
        ///By default the Server Info Bar shows:
        ///- Whether Auto-Rotation is on or off
        ///- (if on) The number of active Auto-Mode Combos
        ///- (if applicable) Whether another plugin is controlling the state of Auto-Rotation..
        /// </summary>
        internal static string ShortDTRText_helpMark {
            get {
                return ResourceManager.GetString("ShortDTRText_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shorten Server Info Bar Text.
        /// </summary>
        internal static string ShortDTRText_Name {
            get {
                return ResourceManager.GetString("ShortDTRText_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        internal static string ShortDTRText_recommendedValue {
            get {
                return ResourceManager.GetString("ShortDTRText_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string ShowBorderAroundOptionsWithChildren_defaultValue {
            get {
                return ResourceManager.GetString("ShowBorderAroundOptionsWithChildren_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will draw a border around Combos and Features that have Features and Options of their own..
        /// </summary>
        internal static string ShowBorderAroundOptionsWithChildren_helpMark {
            get {
                return ResourceManager.GetString("ShowBorderAroundOptionsWithChildren_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Borders around Combos and Features with Options.
        /// </summary>
        internal static string ShowBorderAroundOptionsWithChildren_Name {
            get {
                return ResourceManager.GetString("ShowBorderAroundOptionsWithChildren_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        internal static string ShowBorderAroundOptionsWithChildren_recommendedValue {
            get {
                return ResourceManager.GetString("ShowBorderAroundOptionsWithChildren_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string ShowOpenerDtr_defaultValue {
            get {
                return ResourceManager.GetString("ShowOpenerDtr_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the status of your current opener, if enabled and applicable..
        /// </summary>
        internal static string ShowOpenerDtr_helpMark {
            get {
                return ResourceManager.GetString("ShowOpenerDtr_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opener Status in Server Info Bar.
        /// </summary>
        internal static string ShowOpenerDtr_Name {
            get {
                return ResourceManager.GetString("ShowOpenerDtr_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        internal static string ShowOpenerDtr_recommendedValue {
            get {
                return ResourceManager.GetString("ShowOpenerDtr_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string ShowTargetHighlight_defaultValue {
            get {
                return ResourceManager.GetString("ShowTargetHighlight_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Only used by AST and DNC currently).
        /// </summary>
        internal static string ShowTargetHighlight_extraText {
            get {
                return ResourceManager.GetString("ShowTargetHighlight_extraText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draws a box around party members in the vanilla Party List, when targeted by certain Features..
        /// </summary>
        internal static string ShowTargetHighlight_helpMark {
            get {
                return ResourceManager.GetString("ShowTargetHighlight_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Target Highlighter.
        /// </summary>
        internal static string ShowTargetHighlight_Name {
            get {
                return ResourceManager.GetString("ShowTargetHighlight_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        internal static string ShowTargetHighlight_recommendedValue {
            get {
                return ResourceManager.GetString("ShowTargetHighlight_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string SuppressAutorotCommand_defaultValue {
            get {
                return ResourceManager.GetString("SuppressAutorotCommand_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will hide chat feedback for /qoltweaks auto commands.
        /// </summary>
        internal static string SuppressAutorotCommand_helpMark {
            get {
                return ResourceManager.GetString("SuppressAutorotCommand_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppress Auto-Rotation commands feedback.
        /// </summary>
        internal static string SuppressAutorotCommand_Name {
            get {
                return ResourceManager.GetString("SuppressAutorotCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        internal static string SuppressAutorotCommand_recommendedValue {
            get {
                return ResourceManager.GetString("SuppressAutorotCommand_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string SuppressSetCommands_defaultValue {
            get {
                return ResourceManager.GetString("SuppressSetCommands_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will hide chat feedback for /qoltweaks set and /qoltweaks unset commands.
        ///(Will still show feedback if the command is being overriden by IPC, or fails).
        /// </summary>
        internal static string SuppressSetCommands_helpMark {
            get {
                return ResourceManager.GetString("SuppressSetCommands_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppress Set and Unset commands feedback.
        /// </summary>
        internal static string SuppressSetCommands_Name {
            get {
                return ResourceManager.GetString("SuppressSetCommands_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        internal static string SuppressSetCommands_recommendedValue {
            get {
                return ResourceManager.GetString("SuppressSetCommands_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string TankbusterToast_defaultValue {
            get {
                return ResourceManager.GetString("TankbusterToast_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show a message on-screen whenever a tankbuster is detected, including who it is targeting..
        /// </summary>
        internal static string TankbusterToast_helpMark {
            get {
                return ResourceManager.GetString("TankbusterToast_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Toast on Tankbuster.
        /// </summary>
        internal static string TankbusterToast_Name {
            get {
                return ResourceManager.GetString("TankbusterToast_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        internal static string TankbusterToast_recommendedValue {
            get {
                return ResourceManager.GetString("TankbusterToast_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string TankbusterTTS_defaultValue {
            get {
                return ResourceManager.GetString("TankbusterTTS_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will play a text-to-speech sound clip whenever a tankbuster is detected, including who it is targeting..
        /// </summary>
        internal static string TankbusterTTS_helpMark {
            get {
                return ResourceManager.GetString("TankbusterTTS_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play TTS on Tankbuster.
        /// </summary>
        internal static string TankbusterTTS_Name {
            get {
                return ResourceManager.GetString("TankbusterTTS_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        internal static string TankbusterTTS_recommendedValue {
            get {
                return ResourceManager.GetString("TankbusterTTS_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #808080FF.
        /// </summary>
        internal static string TargetHighlightColor_defaultValue {
            get {
                return ResourceManager.GetString("TargetHighlightColor_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the color of the box drawn around party members..
        /// </summary>
        internal static string TargetHighlightColor_helpMark {
            get {
                return ResourceManager.GetString("TargetHighlightColor_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Highlighter Color.
        /// </summary>
        internal static string TargetHighlightColor_Name {
            get {
                return ResourceManager.GetString("TargetHighlightColor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        internal static string TargetHighlightColor_recommendedValue {
            get {
                return ResourceManager.GetString("TargetHighlightColor_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targeting Options.
        /// </summary>
        internal static string TargetingOptions_Category {
            get {
                return ResourceManager.GetString("TargetingOptions_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        internal static string Throttle_defaultValue {
            get {
                return ResourceManager.GetString("Throttle_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will restrict how often Combos will update the Action on your Hotbar.
        ///At 50ms it&apos;s not really restrictive, always giving you an up to date action.
        ///
        ///If you are looking for some (fairly minor) FPS gains then you can increase this value to make Combos run less often.
        ///This makes your combos less responsive, and perhaps even clips GCDs.
        ///At high values this will clip your GCDs by several seconds or break your rotation altogether..
        /// </summary>
        internal static string Throttle_helpMark {
            get {
                return ResourceManager.GetString("Throttle_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Updater Throttle.
        /// </summary>
        internal static string Throttle_Name {
            get {
                return ResourceManager.GetString("Throttle_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20-200.
        /// </summary>
        internal static string Throttle_recommendedValue {
            get {
                return ResourceManager.GetString("Throttle_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milliseconds.
        /// </summary>
        internal static string Throttle_unitLabel {
            get {
                return ResourceManager.GetString("Throttle_unitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troubleshooting Options.
        /// </summary>
        internal static string TroubleshootingOptions_Category {
            get {
                return ResourceManager.GetString("TroubleshootingOptions_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string UIShowPresetIDs_defaultValue {
            get {
                return ResourceManager.GetString("UIShowPresetIDs_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the Preset ID number next to the name of each Combo and Feature.
        ///These are the IDs used for commands like `/qoltweaks toggle &lt;ID&gt;`.
        ///Pre-7.3 the behavior was to show a number here, but it was much shorter, and did not work in commands..
        /// </summary>
        internal static string UIShowPresetIDs_helpMark {
            get {
                return ResourceManager.GetString("UIShowPresetIDs_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Preset IDs next to Combo Names.
        /// </summary>
        internal static string UIShowPresetIDs_Name {
            get {
                return ResourceManager.GetString("UIShowPresetIDs_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string UIShowPresetIDs_recommendedValue {
            get {
                return ResourceManager.GetString("UIShowPresetIDs_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string UIShowSearchBar_defaultValue {
            get {
                return ResourceManager.GetString("UIShowSearchBar_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether Search Bars should be shown in Settings, and PvE and PvP Jobs..
        /// </summary>
        internal static string UIShowSearchBar_helpMark {
            get {
                return ResourceManager.GetString("UIShowSearchBar_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Search Bars.
        /// </summary>
        internal static string UIShowSearchBar_Name {
            get {
                return ResourceManager.GetString("UIShowSearchBar_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string UIShowSearchBar_recommendedValue {
            get {
                return ResourceManager.GetString("UIShowSearchBar_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string UseCustomHealStack_defaultValue {
            get {
                return ResourceManager.GetString("UseCustomHealStack_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this if you would rather make your own stack of target priorities for Heal Targets instead of using our default stack.
        ///
        ///It is recommended to use this to align with your Redirect/Reaction configuration IF you&apos;re not using the Retarget Healing Actions option above; otherwise it is preference..
        /// </summary>
        internal static string UseCustomHealStack_helpMark {
            get {
                return ResourceManager.GetString("UseCustomHealStack_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a Custom Heal Stack Instead.
        /// </summary>
        internal static string UseCustomHealStack_Name {
            get {
                return ResourceManager.GetString("UseCustomHealStack_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        internal static string UseCustomHealStack_recommendedValue {
            get {
                return ResourceManager.GetString("UseCustomHealStack_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string UseFieldMouseoverOverridesInDefaultHealStack_defaultValue {
            get {
                return ResourceManager.GetString("UseFieldMouseoverOverridesInDefaultHealStack_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will add any MouseOver targets to the top of the Default Heal Stack, overriding the rest of the stack if you are mousing over any party member UI.
        ///
        ///It is recommended to enable this if you are a keyboard+mouse user and enable Retarget Healing Actions (or have UI MouseOver targets in your Redirect/Reaction configuration)..
        /// </summary>
        internal static string UseFieldMouseoverOverridesInDefaultHealStack_helpMark {
            get {
                return ResourceManager.GetString("UseFieldMouseoverOverridesInDefaultHealStack_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Field MouseOver to the Default Healing Stack.
        /// </summary>
        internal static string UseFieldMouseoverOverridesInDefaultHealStack_Name {
            get {
                return ResourceManager.GetString("UseFieldMouseoverOverridesInDefaultHealStack_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        internal static string UseFieldMouseoverOverridesInDefaultHealStack_recommendedValue {
            get {
                return ResourceManager.GetString("UseFieldMouseoverOverridesInDefaultHealStack_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string UseFocusTargetOverrideInDefaultHealStack_defaultValue {
            get {
                return ResourceManager.GetString("UseFocusTargetOverrideInDefaultHealStack_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will add your focus target under your hard and soft targets in the Default Heal Stack, overriding the rest of the stack if you have a living focus target..
        /// </summary>
        internal static string UseFocusTargetOverrideInDefaultHealStack_helpMark {
            get {
                return ResourceManager.GetString("UseFocusTargetOverrideInDefaultHealStack_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Focus Target to the Default Healing Stack.
        /// </summary>
        internal static string UseFocusTargetOverrideInDefaultHealStack_Name {
            get {
                return ResourceManager.GetString("UseFocusTargetOverrideInDefaultHealStack_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        internal static string UseFocusTargetOverrideInDefaultHealStack_recommendedValue {
            get {
                return ResourceManager.GetString("UseFocusTargetOverrideInDefaultHealStack_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string UseLowestHPOverrideInDefaultHealStack_defaultValue {
            get {
                return ResourceManager.GetString("UseLowestHPOverrideInDefaultHealStack_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will add a nearby party member with the lowest HP% to bottom of the Default Heal Stack, overriding only yourself..
        /// </summary>
        internal static string UseLowestHPOverrideInDefaultHealStack_helpMark {
            get {
                return ResourceManager.GetString("UseLowestHPOverrideInDefaultHealStack_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Lowest HP% Ally to the Default Healing Stack.
        /// </summary>
        internal static string UseLowestHPOverrideInDefaultHealStack_Name {
            get {
                return ResourceManager.GetString("UseLowestHPOverrideInDefaultHealStack_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        internal static string UseLowestHPOverrideInDefaultHealStack_recommendedValue {
            get {
                return ResourceManager.GetString("UseLowestHPOverrideInDefaultHealStack_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlike the other Default+ Options, this one is not an option in most other Retargeting Plugins.
        ///THIS SHOULD BE USED WITH THE &apos;RETARGET HEALING ACTIONS&apos; SETTING ABOVE!.
        /// </summary>
        internal static string UseLowestHPOverrideInDefaultHealStack_warningMark {
            get {
                return ResourceManager.GetString("UseLowestHPOverrideInDefaultHealStack_warningMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string UseUIMouseoverOverridesInDefaultHealStack_defaultValue {
            get {
                return ResourceManager.GetString("UseUIMouseoverOverridesInDefaultHealStack_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will add any UI MouseOver targets to the top of the Default Heal Stack, overriding the rest of the stack if you are mousing over any party member UI.
        ///
        ///It is recommended to enable this if you are a keyboard+mouse user and enable Retarget Healing Actions (or have UI MouseOver targets in your Redirect/Reaction configuration)..
        /// </summary>
        internal static string UseUIMouseoverOverridesInDefaultHealStack_helpMark {
            get {
                return ResourceManager.GetString("UseUIMouseoverOverridesInDefaultHealStack_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add UI MouseOver to the Default Healing Stack.
        /// </summary>
        internal static string UseUIMouseoverOverridesInDefaultHealStack_Name {
            get {
                return ResourceManager.GetString("UseUIMouseoverOverridesInDefaultHealStack_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        internal static string UseUIMouseoverOverridesInDefaultHealStack_recommendedValue {
            get {
                return ResourceManager.GetString("UseUIMouseoverOverridesInDefaultHealStack_recommendedValue", resourceCulture);
            }
        }
    }
}
