//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrathCombo.Resources.Localization.UI.Settings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WrathCombo.Resources.Localization.UI.Settings.SettingsUI", typeof(SettingsUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Debug File.
        /// </summary>
        internal static string Button_CreateDebug {
            get {
                return ResourceManager.GetString("Button_CreateDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tab allows you to customise global settings for QoL Tweaks..
        /// </summary>
        internal static string Header_SettingsAbout {
            get {
                return ResourceManager.GetString("Header_SettingsAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will generate a debug file on your desktop.
        ///Useful to give developers to help troubleshoot issues.
        ///The same as using the following command: /qoltweaks debug.
        /// </summary>
        internal static string HelpText_CreateDebug {
            get {
                return ResourceManager.GetString("HelpText_CreateDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the order in which QoL Tweaks will try to select a healing target. 
        ///If the &apos;Retarget Healing Actions&apos; option is disabled, that is just the target that will be used for checking the HP threshold to trigger different healing actions to show up in their rotations. 
        ///That means that if your own retargeting solution (Redirect, Reaction, etc) does not match this then QoL Tweaks can stick you in a loop of healing the wrong target!!! 
        ///If the &apos;Retarget Healing Actions&apos; option is enabled, that target is also the one  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpText_HealStack {
            get {
                return ResourceManager.GetString("HelpText_HealStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the order in which QoL Tweaks will try to select a raise target,
        ///if Retargeting of any Raise Feature is enabled..
        /// </summary>
        internal static string HelpText_RaiseStack {
            get {
                return ResourceManager.GetString("HelpText_RaiseStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Feature will involve retargeting actions if enabled..
        /// </summary>
        internal static string HelpText_Retargetting1 {
            get {
                return ResourceManager.GetString("HelpText_Retargetting1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The actions this Feature affects will automatically be
        ///targeted onto the targets in the priority you have configured..
        /// </summary>
        internal static string HelpText_Retargetting2 {
            get {
                return ResourceManager.GetString("HelpText_Retargetting2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using plugins like Redirect or Reaction with configurations
        ///affecting the same actions will Conflict and may cause issues..
        /// </summary>
        internal static string HelpText_Retargetting3 {
            get {
                return ResourceManager.GetString("HelpText_Retargetting3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name, Setting name, Internal Name, etc.
        /// </summary>
        internal static string Info_searchHintText {
            get {
                return ResourceManager.GetString("Info_searchHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Heal Stack:.
        /// </summary>
        internal static string Label_HealStack {
            get {
                return ResourceManager.GetString("Label_HealStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Raise Stack:.
        /// </summary>
        internal static string Label_RaiseStack {
            get {
                return ResourceManager.GetString("Label_RaiseStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        internal static string Label_searchLabelText {
            get {
                return ResourceManager.GetString("Label_searchLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Value:.
        /// </summary>
        internal static string Text_DefaultValue {
            get {
                return ResourceManager.GetString("Text_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Value:.
        /// </summary>
        internal static string Text_RecommendedValue {
            get {
                return ResourceManager.GetString("Text_RecommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOU are responsible for making sure your retargeting solution matches this heal stack!
        ///If it does not then QoL Tweaks can get stuck in a loop where X player is checked and needs healing, but Y player is who gets healed!.
        /// </summary>
        internal static string Warning_HealStack {
            get {
                return ResourceManager.GetString("Warning_HealStack", resourceCulture);
            }
        }
    }
}
